In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import re

In [160]:
df=pd.read_csv(r"C:\Users\vamsh\Downloads\SLU Opportunity Wise Data-1710158595043 - SLU Opportunity Wise Data-1710158595043.csv")
df

,Profile Id,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Last Name,Date of Birth,Gender,...,Status Code,Apply Date,Opportunity Start Date,Reward Awarded Date,Completion Date,Reward Amount,Badge Id,Badge Name,Skill Points Earned,Skills Earned
0,004b8a25-17d4-4e9a-a41b-b5336327e170,06/14/2023 12:30:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Faria,Khan,01/12/2001,Female,...,1080,06/14/2023 12:36:09,11/03/2022 18:30:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00628747-9775-4a85-a179-4d5007ccb8b7,05/01/2023 05:29:16,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Poojitha,Bembadi,08/16/2000,Female,...,1080,05/01/2023 06:08:21,11/03/2022 18:30:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00841155-6c62-4f83-b165-57ba0df9c031,04/09/2023 20:35:08,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Emmanuel,Thompson,01/27/2002,Male,...,1080,05/11/2023 1085640:21:29,11/03/2022 18:30:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00f5161c-ba85-472d-9b0a-3301aac78598,08/29/2023 05:20:03,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Amrutha Varshini,Anagurthi,11/01/1999,Female,...,1070,10/09/2023 22:02:42,11/03/2022 18:30:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01273a5e-fcc5-4b1a-a637-19aff497dac1,01/06/2023 15:26:36,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Vinay Varshith,Pechetti,04/19/2000,Male,...,1080,01/06/2023 15:40:10,11/03/2022 18:30:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8553,f9f62826-54ba-4911-8b72-226bda509ad8,03/05/2024 16:39:21,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,03/08/2024 11:30:00,Selam,Endale,10/14/2006,Female,...,1070,03/05/2024 17:10:41,03/08/2024 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8554,fbc5c29d-4bfe-4056-adb9-a91e0f537b74,03/06/2024 15:58:47,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,03/08/2024 11:30:00,Gowri Sailesh,Kotipalli,05/18/1999,Male,...,1070,03/06/2024 18:22:11,03/08/2024 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8555,fc54550e-fb48-41f8-8e9d-f224868edfa5,02/29/2024 15:02:31,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,03/08/2024 11:30:00,Abiola,Ibrahim,03/16/1999,Male,...,1070,02/29/2024 15:10:06,03/08/2024 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8556,fe592afe-3d80-41d4-abcd-ce2c943e7b2f,12/23/2023 03:53:12,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,03/08/2024 11:30:00,venumadhavi,bogireddy,06/05/1997,Female,...,1070,02/27/2024 06:48:47,03/08/2024 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8557,fecf5e0c-5403-4fb7-ba5c-55b041208514,06/01/2023 13:22:01,00000000-10GQ-RJHT-3G4S-BKGBY1,Freelance Mastery workshop,Event,03/08/2024 11:30:00,Prashanth Reddy,Varanganti,11/30/2000,Male,...,1070,02/16/2024 16:33:00,03/08/2024 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
df.shape

(8558, 33)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8558 entries, 0 to 8557
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Profile Id               8558 non-null   object
 1   Learner SignUp DateTime  8558 non-null   object
 2   Opportunity Id           8558 non-null   object
 3   Opportunity Name         8558 non-null   object
 4   Opportunity Category     8558 non-null   object
 5   Opportunity End Date     8558 non-null   object
 6   First Name               8558 non-null   object
 7   Last Name                8558 non-null   object
 8   Date of Birth            8558 non-null   object
 9   Gender                   8558 non-null   object
 10  Mobile Number            8558 non-null   object
 11  Address Line 1           8554 non-null   object
 12  Address Line 2           3553 non-null   object
 13  City                     8557 non-null   object
 14  State                    8555 non-null   object
 15  Country                  8558 non-null   object
 16  Zip Code                 8555 non-null   object
 17  Institution Name         8553 non-null   object
 18  Graduation Date          8558 non-null   object
 19  Current Student Status   8558 non-null   object
 20  Current/Intended Major   8553 non-null   object
 21  Entry created at         8558 non-null   object
 22  Status Description       8558 non-null   object
 23  Status Code              8558 non-null   int64
 24  Apply Date               8558 non-null   object
 25  Opportunity Start Date   4764 non-null   object
 26  Reward Awarded Date      29 non-null     object
 27  Completion Date          29 non-null     object
 28  Reward Amount            29 non-null     float64
 29  Badge Id                 29 non-null     object
 30  Badge Name               29 non-null     object
 31  Skill Points Earned      29 non-null     float64
 32  Skills Earned            29 non-null     object
dtypes: float64(2), int64(1), object(30)
memory usage: 2.2+ MB

In [50]:
df.describe()

       Status Code  Reward Amount  Skill Points Earned
count  8558.000000      29.000000            29.000000
mean   1052.225987      86.206897           363.068966
std      21.665207      65.324126           436.942292
min    1010.000000      50.000000            50.000000
25%    1030.000000      50.000000            50.000000
50%    1050.000000      50.000000           137.000000
75%    1070.000000      50.000000          1052.000000
max    1120.000000     200.000000          1052.000000

Data Cleaning

Handling missing values

In [51]:
df.isnull().sum()

Profile Id                    0
Learner SignUp DateTime       0
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date          0
First Name                    0
Last Name                     0
Date of Birth                 0
Gender                        0
Mobile Number                 0
Address Line 1                4
Address Line 2             5005
City                          1
State                         3
Country                       0
Zip Code                      3
Institution Name              5
Graduation Date               0
Current Student Status        0
Current/Intended Major        5
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                    0
Opportunity Start Date     3794
Reward Awarded Date        8529
Completion Date            8529
Reward Amount              8529
Badge Id                   8529
Badge Name                 8529
Skill Points Earned        8529
Skills Earned              8529
dtype: int64

In [52]:
df.nunique()

Profile Id                 3964
Learner SignUp DateTime    3916
Opportunity Id               23
Opportunity Name             22
Opportunity Category          5
Opportunity End Date         17
First Name                 3026
Last Name                  3092
Date of Birth              2620
Gender                        4
Mobile Number              3834
Address Line 1             3742
Address Line 2             1552
City                       1341
State                       645
Country                      71
Zip Code                   1907
Institution Name           2089
Graduation Date             243
Current Student Status        4
Current/Intended Major      406
Entry created at             94
Status Description            8
Status Code                   8
Apply Date                 8548
Opportunity Start Date       18
Reward Awarded Date           8
Completion Date               8
Reward Amount                 2
Badge Id                      4
Badge Name                    4
Skill Points Earned           4
Skills Earned                 4
dtype: int64

Here i dont think Address Line 1, Address line 2 will be of much use, so i think of replacing them with Null/Not mentioned,
There is 1 missing in city, 3 in state,3 in zip codes, first ill try to find their values through adjacent city,state,city/adress columns if found then okay else ill remove them directly , since they are very few in numbers.
there are 5 missing in Institution name and Current/Intended Major/Institution Name, most probably ill try to group by country and then take most frequent in that country and replace with them.
There are 3794 null values in the Opportunity start date, here since there is Opportunity End Date, ill try to find if there is any relation between those columns and replace the null values with those reltionship values(i.e days difference).
There are 8529 missing values in Reward Awarded Date,Completion Date,Reward Amount,Badge Id, Badge Name, Skills Points Earned, Skills Earned, actually  these values are present only if the student has completed his course/opportunity, so since these values are missing indicates that, the remaining students have not completed the course.opportunity, so i like to replace with 0 for numerical cols and Null for categorical columns.

In [161]:
# Display index numbers of rows with missing values in specific columns
missing_city = df[df['City'].isnull()].index
missing_state = df[df['State'].isnull()].index
missing_zip_code = df[df['Zip Code'].isnull()].index

print("Indexes with missing values:")
print(f"City: {missing_city.tolist()}")
print(f"State: {missing_state.tolist()}")
print(f"Zip Code: {missing_zip_code.tolist()}")

Indexes with missing values:
City: [2512]
State: [2033, 2512, 4856]
Zip Code: [652, 2108, 2512]

In [110]:
# Filter rows where 'City' is null
missing_city_info = df[df['City'].isnull()]

# Select relevant columns to display
columns_to_display = ['Country', 'State', 'City', 'Address Line 1', 'Address Line 2','Zip Code']
print(missing_city_info[columns_to_display])

     Country State City Address Line 1 Address Line 2 Zip Code
2512   Ghana   NaN  NaN            NaN            NaN      NaN

In [111]:
# Filter rows with missing values in 'City', 'State', or 'Zip Code'
missing_city_info = df[df['City'].isnull()]
missing_state_info = df[df['State'].isnull()]
missing_zip_code_info = df[df['Zip Code'].isnull()]

# Select relevant columns to display
columns_to_display = ['Country', 'State', 'City', 'Address Line 1', 'Address Line 2', 'Zip Code']

print("Missing City Information:")
print(missing_city_info[columns_to_display], "\n")

print("Missing State Information:")
print(missing_state_info[columns_to_display], "\n")

print("Missing Zip Code Information:")
print(missing_zip_code_info[columns_to_display])

Missing City Information:
     Country State City Address Line 1 Address Line 2 Zip Code
2512   Ghana   NaN  NaN            NaN            NaN      NaN

Missing State Information:
     Country State   City               Address Line 1 Address Line 2 Zip Code
2033   Egypt   NaN   Giza                          NaN            NaN    12655
2512   Ghana   NaN    NaN                          NaN            NaN      NaN
4856   Ghana   NaN  ACCRA  P.O.BOX NT 461ACCRA NEWTOWN  ACCRA NEWTOWN      233

Missing Zip Code Information:
       Country      State     City      Address Line 1      Address Line 2  \
652     Uganda    Mbarara  Mbarara       +256756822742                 NaN
2108  Cameroon  Northwest  Bamenda  Behind che Bamenda  New road buea town
2512     Ghana        NaN      NaN                 NaN                 NaN

     Zip Code
652       NaN
2108      NaN
2512      NaN

Here from zipcode: 12655 i know that it belongs to Cario,
And since Ghana is a country which is not divided into states but regions and here no zipcodes(but sometimes they use 233 or 00223- which is their international calling code", but capital is ACCRA city, so we replace null values with Accra and zip codes with 233, inorder to not to ddrop it.

Ghana, replace state with ACCRA city,zipcodes with 233
In Egypt , the zipcodes 12655 belongs to Cario State.
In rest of zip codes since we dont know their values replacing them with 000 or dropping them off,

Handling Missing values

In [162]:
# Fill 'Address Line 1' with 'Unknown' if critical
df['Address Line 1'].fillna('Unknown', inplace=True)

# Keep 'Address Line 2' as it is, or fill with an empty string
df['Address Line 2'].fillna('', inplace=True)

C:\Users\vamsh\AppData\Local\Temp\ipykernel_13788\3842928778.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Address Line 1'].fillna('Unknown', inplace=True)
C:\Users\vamsh\AppData\Local\Temp\ipykernel_13788\3842928778.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Address Line 2'].fillna('', inplace=True)

In [163]:
# Replace missing 'City' values with 'Accra' where 'Country' is Ghana
df.loc[df['City'].isnull() & (df['Country'] == 'Ghana'), 'City'] = 'Accra'

In [164]:
# Replace missing 'State' values with 'Cairo' where 'Country' is Egypt and 'Zip Code' is 12655
df.loc[df['State'].isnull() & (df['Country'] == 'Egypt') & (df['Zip Code'] == '12655'), 'State'] = 'Cairo'

# Replace missing 'State' values with 'Greater Accra' where 'Country' is Ghana
df.loc[df['State'].isnull() & (df['Country'] == 'Ghana'), 'State'] = 'Greater Accra'

In [165]:
# 1. Replace missing 'Zip Code' with '233' where 'Country' is Ghana
df.loc[df['Zip Code'].isnull() & (df['Country'] == 'Ghana'), 'Zip Code'] = '233'

# 2. Replace missing 'Zip Code' with '40003' where 'City' is Mbarara
df.loc[df['Zip Code'].isnull() & (df['City'] == 'Mbarara'), 'Zip Code'] = '40003'

# 3. Replace missing 'Zip Code' with '00237' where 'Country' is Cameroon
df.loc[df['Zip Code'].isnull() & (df['Country'] == 'Cameroon'), 'Zip Code'] = '00237'

40003-mbarara
233-ghana
00237-cameroon

In [60]:
print(df.isnull().sum())

Profile Id                    0
Learner SignUp DateTime       0
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date          0
First Name                    0
Last Name                     0
Date of Birth                 0
Gender                        0
Mobile Number                 0
Address Line 1                0
Address Line 2                0
City                          0
State                         0
Country                       0
Zip Code                      0
Institution Name              5
Graduation Date               0
Current Student Status        0
Current/Intended Major        5
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                    0
Opportunity Start Date     3794
Reward Awarded Date        8529
Completion Date            8529
Reward Amount              8529
Badge Id                   8529
Badge Name                 8529
Skill Points Earned        8529
Skills Earned              8529
dtype: int64

In [166]:
# 2. Handle missing values
# For numerical columns, replace null with 0
numerical_columns = ['Reward Amount', 'Skill Points Earned']
df[numerical_columns] = df[numerical_columns].fillna(0)

# For categorical columns, replace null with 'NaN' string
categorical_columns = ['Badge Id', 'Badge Name', 'Skills Earned']
df[categorical_columns] = df[categorical_columns].fillna('NaN')

In [167]:
# Handle Reward Awarded Date and Completion Date
# Replace NaT with a specific date (e.g., '1900-01-01' to indicate it's a placeholder)
placeholder_date = pd.Timestamp('1900-01-01')
df['Reward Awarded Date'].fillna(placeholder_date, inplace=True)
df['Completion Date'].fillna(placeholder_date, inplace=True)

C:\Users\vamsh\AppData\Local\Temp\ipykernel_13788\4206674032.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Reward Awarded Date'].fillna(placeholder_date, inplace=True)
C:\Users\vamsh\AppData\Local\Temp\ipykernel_13788\4206674032.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Completion Date'].fillna(placeholder_date, inplace=True)

In [168]:
# Step 1: Clean and extract valid date formats
cleaned_end_dates = []

for date_str in df['Opportunity End Date']:
    # Check if the value is not NaN
    if pd.notna(date_str):
        # Split on space and take the first part (date portion only)
        date_part = date_str.split()[0]

        # Replace hyphens with slashes for consistency
        date_part = date_part.replace('-', '/')

        # Convert to datetime, extracting only the date part
        try:
            date = pd.to_datetime(date_part, errors='coerce')
            cleaned_end_dates.append(date.date() if pd.notna(date) else None)
        except Exception:
            cleaned_end_dates.append(None)
    else:
        cleaned_end_dates.append(None)

# Step 2: Assign the cleaned dates back to the 'Opportunity End Date' column
df['Opportunity End Date'] = cleaned_end_dates

# Step 3: Verify the changes
print(df.head())

# Optional: Check if there are any remaining missing values
missing_count = df['Opportunity End Date'].isna().sum()
print(f"Missing values after cleaning: {missing_count}")

                             Profile Id Learner SignUp DateTime  \
0  004b8a25-17d4-4e9a-a41b-b5336327e170     06/14/2023 12:30:35
1  00628747-9775-4a85-a179-4d5007ccb8b7     05/01/2023 05:29:16
2  00841155-6c62-4f83-b165-57ba0df9c031     04/09/2023 20:35:08
3  00f5161c-ba85-472d-9b0a-3301aac78598     08/29/2023 05:20:03
4  01273a5e-fcc5-4b1a-a637-19aff497dac1     01/06/2023 15:26:36

                   Opportunity Id  \
0  00000000-0GN2-A0AY-7XK8-C5FZPP
1  00000000-0GN2-A0AY-7XK8-C5FZPP
2  00000000-0GN2-A0AY-7XK8-C5FZPP
3  00000000-0GN2-A0AY-7XK8-C5FZPP
4  00000000-0GN2-A0AY-7XK8-C5FZPP

                                    Opportunity Name Opportunity Category  \
0  Career Essentials: Getting Started with Your P...               Course
1  Career Essentials: Getting Started with Your P...               Course
2  Career Essentials: Getting Started with Your P...               Course
3  Career Essentials: Getting Started with Your P...               Course
4  Career Essentials: Getting Started with Your P...               Course

  Opportunity End Date        First Name  Last Name Date of Birth  Gender  \
0           2024-06-29             Faria       Khan    01/12/2001  Female
1           2024-06-29          Poojitha    Bembadi    08/16/2000  Female
2           2024-06-29          Emmanuel   Thompson    01/27/2002    Male
3           2024-06-29  Amrutha Varshini  Anagurthi    11/01/1999  Female
4           2024-06-29    Vinay Varshith   Pechetti    04/19/2000    Male

   ... Status Code                Apply Date Opportunity Start Date  \
0  ...        1080       06/14/2023 12:36:09    11/03/2022 18:30:39
1  ...        1080       05/01/2023 06:08:21    11/03/2022 18:30:39
2  ...        1080  05/11/2023 1085640:21:29    11/03/2022 18:30:39
3  ...        1070       10/09/2023 22:02:42    11/03/2022 18:30:39
4  ...        1080       01/06/2023 15:40:10    11/03/2022 18:30:39

   Reward Awarded Date      Completion Date Reward Amount Badge Id Badge Name  \
0  1900-01-01 00:00:00  1900-01-01 00:00:00           0.0      NaN        NaN
1  1900-01-01 00:00:00  1900-01-01 00:00:00           0.0      NaN        NaN
2  1900-01-01 00:00:00  1900-01-01 00:00:00           0.0      NaN        NaN
3  1900-01-01 00:00:00  1900-01-01 00:00:00           0.0      NaN        NaN
4  1900-01-01 00:00:00  1900-01-01 00:00:00           0.0      NaN        NaN

  Skill Points Earned Skills Earned
0                 0.0           NaN
1                 0.0           NaN
2                 0.0           NaN
3                 0.0           NaN
4                 0.0           NaN

[5 rows x 33 columns]
Missing values after cleaning: 0

In [169]:

# Convert date columns to datetime
date_columns = ['Opportunity Start Date', 'Opportunity End Date', 'Reward Awarded Date', 'Completion Date']
for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')

# Handle Opportunity Start Date
# Calculate the median duration between start and end dates for non-null pairs
valid_duration = df['Opportunity End Date'] - df['Opportunity Start Date']
median_duration = valid_duration.dropna().median()

# Fill missing start dates by subtracting the median duration from the end date
df.loc[df['Opportunity Start Date'].isnull(), 'Opportunity Start Date'] = df['Opportunity End Date'] - median_duration

In [170]:
# Find rows with missing values in 'Institution Name' and 'Current/Intended Major'
missing_institution = df[df['Institution Name'].isna()][['Profile Id', 'Institution Name', 'Country', 'State', 'City', 'Address Line 1', 'Address Line 2']]
missing_major = df[df['Current/Intended Major'].isna()][['Profile Id', 'Current/Intended Major', 'Country', 'State', 'City', 'Address Line 1', 'Address Line 2']]

# Display the results
print("Missing Institution Name:")
print(missing_institution)

print("\nMissing Current/Intended Major:")
print(missing_major)

Missing Institution Name:
                                Profile Id Institution Name Country  \
239   2dee01e7-29c5-49aa-ae14-8104b83e0f82              NaN   India
1746  87d3c4b1-e736-4f5a-aeec-435aa17cf694              NaN   Ghana
3347  2dee01e7-29c5-49aa-ae14-8104b83e0f82              NaN   India
4994  fc9de531-ee69-44ad-93ab-df6b99246f2f              NaN   India
6021  2dee01e7-29c5-49aa-ae14-8104b83e0f82              NaN   India

          State       City                                     Address Line 1  \
239   telangana  hyderabad  Srisai Towers G-1 Kalyan Nagar East Anandbagh ...
1746      Accra      Accra                                         Hfc Estate
3347  telangana  hyderabad  Srisai Towers G-1 Kalyan Nagar East Anandbagh ...
4994  Karnataka  Bangalore     L-30  3rd Stage  Kec Colony  Basaveshwaranagar
6021  telangana  hyderabad  Srisai Towers G-1 Kalyan Nagar East Anandbagh ...

     Address Line 2
239      Malkajgiri
1746
3347     Malkajgiri
4994
6021     Malkajgiri

Missing Current/Intended Major:
                                Profile Id Current/Intended Major  \
1256  dfe47fe1-6892-4406-ba5f-c09b24a4371d                    NaN
1651  59309ddb-1962-46ab-ad6e-cbde8cc23133                    NaN
3362  34aff498-dc91-43e5-858b-01f6556e3fd6                    NaN
4454  70fb0222-f199-4d10-b3b2-385a1a8acf9f                    NaN
4996  fd0f2846-4024-43ae-96af-2475d8305ce4                    NaN

            Country        State          City  \
1256       Pakistan       saddar        lahore
1651  United States     Missouri     Catawissa
3362        Nigeria  RiversState  PortHarcourt
4454          India  MAHARASHTRA   NAVI MUMBAI
4996          India        Assam      Guwahati

                                         Address Line 1 Address Line 2
1256                                           pakistan         punjab
1651                                    552 Court Carol
3362                                         8138021245
4454       EKTA CHS  B-13 1:1  SECTOR-9  KOPAR KHAIRANE
4996  Kalapahar  Cycle Factory Tinali  Esha Port  2n...

In [171]:
# Get the most frequent 'Institution Name' for each city
institution_mode = df.groupby('City')['Institution Name'].agg(lambda x: x.mode()[0] if not x.mode().empty else 'Unknown Institution')

# Replace missing values in 'Institution Name' with the mode
for index in df[df['Institution Name'].isna()].index:
    city = df.loc[index, 'City']
    df.loc[index, 'Institution Name'] = institution_mode.get(city, 'Unknown Institution')

In [172]:
# Get the overall most frequent value for 'Current/Intended Major'
major_mode = df['Current/Intended Major'].mode()[0] if not df['Current/Intended Major'].mode().empty else 'Undecided'

# Replace missing values in 'Current/Intended Major'
df['Current/Intended Major'].fillna(major_mode, inplace=True)

C:\Users\vamsh\AppData\Local\Temp\ipykernel_13788\1686523699.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Current/Intended Major'].fillna(major_mode, inplace=True)

In [68]:
df.shape

(8558, 33)

In [69]:
df.head()

,Profile Id,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Last Name,Date of Birth,Gender,...,Status Code,Apply Date,Opportunity Start Date,Reward Awarded Date,Completion Date,Reward Amount,Badge Id,Badge Name,Skill Points Earned,Skills Earned
0,004b8a25-17d4-4e9a-a41b-b5336327e170,06/14/2023 12:30:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29,Faria,Khan,01/12/2001,Female,...,1080,06/14/2023 12:36:09,2022-11-03 18:30:39,1900-01-01,1900-01-01,0.0,NaN,NaN,0.0,NaN
1,00628747-9775-4a85-a179-4d5007ccb8b7,05/01/2023 05:29:16,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29,Poojitha,Bembadi,08/16/2000,Female,...,1080,05/01/2023 06:08:21,2022-11-03 18:30:39,1900-01-01,1900-01-01,0.0,NaN,NaN,0.0,NaN
2,00841155-6c62-4f83-b165-57ba0df9c031,04/09/2023 20:35:08,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29,Emmanuel,Thompson,01/27/2002,Male,...,1080,05/11/2023 1085640:21:29,2022-11-03 18:30:39,1900-01-01,1900-01-01,0.0,NaN,NaN,0.0,NaN
3,00f5161c-ba85-472d-9b0a-3301aac78598,08/29/2023 05:20:03,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29,Amrutha Varshini,Anagurthi,11/01/1999,Female,...,1070,10/09/2023 22:02:42,2022-11-03 18:30:39,1900-01-01,1900-01-01,0.0,NaN,NaN,0.0,NaN
4,01273a5e-fcc5-4b1a-a637-19aff497dac1,01/06/2023 15:26:36,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29,Vinay Varshith,Pechetti,04/19/2000,Male,...,1080,01/06/2023 15:40:10,2022-11-03 18:30:39,1900-01-01,1900-01-01,0.0,NaN,NaN,0.0,NaN

In [70]:
df.isnull().sum()

Profile Id                 0
Learner SignUp DateTime    0
Opportunity Id             0
Opportunity Name           0
Opportunity Category       0
Opportunity End Date       0
First Name                 0
Last Name                  0
Date of Birth              0
Gender                     0
Mobile Number              0
Address Line 1             0
Address Line 2             0
City                       0
State                      0
Country                    0
Zip Code                   0
Institution Name           0
Graduation Date            0
Current Student Status     0
Current/Intended Major     0
Entry created at           0
Status Description         0
Status Code                0
Apply Date                 0
Opportunity Start Date     0
Reward Awarded Date        0
Completion Date            0
Reward Amount              0
Badge Id                   0
Badge Name                 0
Skill Points Earned        0
Skills Earned              0
dtype: int64

In [71]:
df.dtypes

Profile Id                         object
Learner SignUp DateTime            object
Opportunity Id                     object
Opportunity Name                   object
Opportunity Category               object
Opportunity End Date       datetime64[ns]
First Name                         object
Last Name                          object
Date of Birth                      object
Gender                             object
Mobile Number                      object
Address Line 1                     object
Address Line 2                     object
City                               object
State                              object
Country                            object
Zip Code                           object
Institution Name                   object
Graduation Date                    object
Current Student Status             object
Current/Intended Major             object
Entry created at                   object
Status Description                 object
Status Code                         int64
Apply Date                         object
Opportunity Start Date     datetime64[ns]
Reward Awarded Date        datetime64[ns]
Completion Date            datetime64[ns]
Reward Amount                     float64
Badge Id                           object
Badge Name                         object
Skill Points Earned               float64
Skills Earned                      object
dtype: object

In [72]:
df['Opportunity End Date'].head()

0   2024-06-29
1   2024-06-29
2   2024-06-29
3   2024-06-29
4   2024-06-29
Name: Opportunity End Date, dtype: datetime64[ns]

In [73]:
df['Date of Birth'].head()

0    01/12/2001
1    08/16/2000
2    01/27/2002
3    11/01/1999
4    04/19/2000
Name: Date of Birth, dtype: object

In [74]:
df['Graduation Date'].head()

0    11/2023
1    05/2025
2    01/2025
3    05/2025
4    12/2024
Name: Graduation Date, dtype: object

In [75]:
df['Apply Date'].head()

0         06/14/2023 12:36:09
1         05/01/2023 06:08:21
2    05/11/2023 1085640:21:29
3         10/09/2023 22:02:42
4         01/06/2023 15:40:10
Name: Apply Date, dtype: object

In [76]:
df['Opportunity Start Date'].head()

0   2022-11-03 18:30:39
1   2022-11-03 18:30:39
2   2022-11-03 18:30:39
3   2022-11-03 18:30:39
4   2022-11-03 18:30:39
Name: Opportunity Start Date, dtype: datetime64[ns]

In [77]:
df['Reward Awarded Date'].head()

0   1900-01-01
1   1900-01-01
2   1900-01-01
3   1900-01-01
4   1900-01-01
Name: Reward Awarded Date, dtype: datetime64[ns]

In [78]:
df['Completion Date'].head()

0   1900-01-01
1   1900-01-01
2   1900-01-01
3   1900-01-01
4   1900-01-01
Name: Completion Date, dtype: datetime64[ns]

In [79]:
df['Learner SignUp DateTime'].head()

0    06/14/2023 12:30:35
1    05/01/2023 05:29:16
2    04/09/2023 20:35:08
3    08/29/2023 05:20:03
4    01/06/2023 15:26:36
Name: Learner SignUp DateTime, dtype: object

In [173]:
# Extract only the date part
df['Opportunity End Date'] = df['Opportunity End Date'].dt.date

In [81]:
df['Opportunity End Date'].head()

0    2024-06-29
1    2024-06-29
2    2024-06-29
3    2024-06-29
4    2024-06-29
Name: Opportunity End Date, dtype: object

In [174]:
# Define a function to convert the date formats
def convert_date_format(date):
    for fmt in ("%m/%d/%Y", "%d-%m-%Y"):  # Add more formats if needed
        try:
            return pd.to_datetime(date, format=fmt)
        except ValueError:
            continue
    return pd.NaT  # Return NaT if no format matches

# Apply the function to the 'Date of Birth' column
df['Date of Birth'] = df['Date of Birth'].apply(convert_date_format)

# Extract only the date part
df['Date of Birth'] = df['Date of Birth'].dt.date

In [83]:
df['Date of Birth'].head()

0    2001-01-12
1    2000-08-16
2    2002-01-27
3    1999-11-01
4    2000-04-19
Name: Date of Birth, dtype: object

In [84]:
# Print unique values in the Graduation Date column
print(df['Graduation Date'].unique())

['11/2023' '05/2025' '01/2025' '12/2024' '05/2028' '12/2025' '04/2024'
 '07/2028' '01/2023' '09/2019' '01/2021' '03/2021' '08/2022' '05/2024'
 '02/2023' '10/2018' '02/2017' '12/2020' '11/2020' '09/2022' '12/2017'
 '05/2026' '06/2023' '06/2024' '01/2024' '06/2022' '03/2024' '07/2020'
 '08/2023' '10/2026' '06/2010' '07/2027' '12/2021' '08/2025' '05/2023'
 '07/2018' '04/2023' '07/2026' '04/2022' '08/2020' '03/2022' '06/2019'
 '02/2022' '05/2011' '12/2022' '12/2023' '09/2025' '06/2025' '12/2018'
 '09/2021' '05/2018' '10/2023' '09/2023' '05/2020' '08/2024' '06/2007'
 '08/2026' '10/2024' '03/2016' '06/2021' '07/2023' '04/2014' '03/2013'
 '10/2010' '01/2026' '11/2024' '11/2022' '05/2027' '10/2016' '01/2016'
 '02/2024' '06/2027' '04/2025' '07/2022' '05/2017' '06/2015' '04/2019'
 '08/2019' '04/1991' '10/2021' '07/2015' '04/2021' '09/2020' '08/2027'
 '03/2020' '03/2026' '12/2013' '10/2022' '01/2020' '09/2024' '03/2023'
 '02/2025' '06/2008' '06/2020' '07/2025' '01/2022' '10/2025' '07/2019'
 '11/2002' '03/2004' '04/2018' '12/2026' '09/2018' '01/2028' '06/2026'
 '07/2024' '03/2025' '04/2026' '08/2021' '07/2021' '01/1995' '05/2003'
 '06/2009' '11/2018' '01/2019' '10/2020' '11/2021' '10/2030' '02/2018'
 '06/2014' '05/2008' '05/2016' '01/2027' '06/2018' '08/2018' '02/2012'
 '01/2004' '08/2015' '05/2022' '10/2017' '05/2021' '07/2017' '11/2025'
 '12/2027' '11/2008' '09/2026' '08/2014' '02/2028' '11/2014' '01/2012'
 '01/2015' '06/2017' '11/2019' '07/2011' '11/2016' '11/2010' '11/2030'
 '08/2017' '05/2014' '05/2019' '10/2013' '10/2005' '01/2011' '06/2012'
 '07/2014' '06/2028' '09/2016' '09/2012' '10/2009' '03/2019' '02/2026'
 '08/2016' '11/2015' '04/2027' '07/2016' '07/2013' '10/2019' '10/2027'
 '04/2011' '04/2004' '05/2009' '04/2030' '11/2017' '07/2010' '08/2028'
 '05/1994' '02/2021' '06/2016' '07/2009' '05/2012' '01/0205' '06/2002'
 '02/2016' '11/2026' '09/2017' '02/2019' '06/2029' '10/2012' '12/2019'
 '12/1989' '12/2006' '05/2015' '05/2013' '09/2027' '09/1998' '09/2028'
 '07/2012' '12/2016' '02/2020' '06/2013' '04/2008' '06/1998' '01/2001'
 '01/2013' '03/2028' '01/2018' '12/2012' '09/2004' '12/2004' '04/2009'
 '01/2010' '11/2027' '12/2011' '08/2008' '03/2027' '10/2008' '03/2017'
 '04/2020' '08/2012' '01/2029' '12/2007' '07/2002' '01/2005' '10/2015'
 '05/2007' '10/2014' '07/2007' '03/2018' '06/2004' '02/2014' '09/2007'
 '12/2015' '12/2028' '05/2010' '09/2001' '12/2001' '01/2002' '04/2017'
 '07/2005' '02/2027' '01/2008' '09/2005' '09/2015']

In [175]:
# Replace invalid date(s)
df['Graduation Date'] = df['Graduation Date'].replace('01/0205', '01/2025')

# Convert to datetime format
df['Graduation Date'] = pd.to_datetime(df['Graduation Date'], format='%m/%Y', errors='coerce')

df['Graduation Date'].head()

0   2023-11-01
1   2025-05-01
2   2025-01-01
3   2025-05-01
4   2024-12-01
Name: Graduation Date, dtype: datetime64[ns]

In [176]:
# Step 1: Clean and extract valid date formats
cleaned_dates = []
for date_str in df['Apply Date']:
    # Split on space and take the first part
    date_part = date_str.split()[0]

    # Replace hyphens with slashes for consistency
    date_part = date_part.replace('-', '/')

    # Convert to datetime
    try:
        date = pd.to_datetime(date_part, errors='coerce')
        cleaned_dates.append(date.date() if pd.notna(date) else None)
    except Exception:
        cleaned_dates.append(None)

# Assign the cleaned dates back to the 'Apply Date' column
df['Apply Date'] = cleaned_dates

# Check the DataFrame to confirm the changes
print(df['Apply Date'].head())

C:\Users\vamsh\AppData\Local\Temp\ipykernel_13788\2620686247.py:12: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  date = pd.to_datetime(date_part, errors='coerce')

0    2023-06-14
1    2023-05-01
2    2023-05-11
3    2023-10-09
4    2023-01-06
Name: Apply Date, dtype: object

In [177]:
# Extract only the date part from the 'Opportunity Start Date' column
df['Opportunity Start Date'] = pd.to_datetime(df['Opportunity Start Date']).dt.date
print(df['Opportunity Start Date'].head())
# Extract only the date part from the 'Reward Awarded Date' column
df['Reward Awarded Date'] = pd.to_datetime(df['Reward Awarded Date']).dt.date
# Check the DataFrame to confirm the changes
print(df['Reward Awarded Date'].head())

0    2022-11-03
1    2022-11-03
2    2022-11-03
3    2022-11-03
4    2022-11-03
Name: Opportunity Start Date, dtype: object
0    1900-01-01
1    1900-01-01
2    1900-01-01
3    1900-01-01
4    1900-01-01
Name: Reward Awarded Date, dtype: object

In [178]:
# Extract only the date part from the 'Completion Date' column
df['Completion Date'] = pd.to_datetime(df['Completion Date']).dt.date
print(df['Completion Date'].head())

0    1900-01-01
1    1900-01-01
2    1900-01-01
3    1900-01-01
4    1900-01-01
Name: Completion Date, dtype: object

In [179]:
# Step 1: Clean and extract valid date formats
cleaned_signup_dates = []
for date_str in df['Learner SignUp DateTime']:
    # Split on space and take the first part (date)
    date_part = date_str.split()[0]

    # Replace hyphens with slashes for consistency
    date_part = date_part.replace('-', '/')

    # Convert to datetime and extract the date
    try:
        date = pd.to_datetime(date_part, errors='coerce')
        cleaned_signup_dates.append(date.date() if pd.notna(date) else None)
    except Exception:
        cleaned_signup_dates.append(None)

# Assign the cleaned dates back to the 'Learner SignUp DateTime' column
df['Learner SignUp DateTime'] = cleaned_signup_dates

# Check if the changes were applied correctly
print(df[['Learner SignUp DateTime']].head())

  Learner SignUp DateTime
0              2023-06-14
1              2023-05-01
2              2023-04-09
3              2023-08-29
4              2023-01-06

In [37]:
df.dtypes

Profile Id                         object
Learner SignUp DateTime            object
Opportunity Id                     object
Opportunity Name                   object
Opportunity Category               object
Opportunity End Date               object
First Name                         object
Last Name                          object
Date of Birth                      object
Gender                             object
Mobile Number                      object
Address Line 1                     object
Address Line 2                     object
City                               object
State                              object
Country                            object
Zip Code                           object
Institution Name                   object
Graduation Date            datetime64[ns]
Current Student Status             object
Current/Intended Major             object
Entry created at                   object
Status Description                 object
Status Code                         int64
Apply Date                         object
Opportunity Start Date             object
Reward Awarded Date                object
Completion Date                    object
Reward Amount                     float64
Badge Id                           object
Badge Name                         object
Skill Points Earned               float64
Skills Earned                      object
dtype: object

In [180]:
# Step 1: Convert 'Reward Amount' and 'Skill Points Earned' to integers
# Handling NaN values by filling them with 0 (optional, adjust if needed)

df['Reward Amount'] = df['Reward Amount'].fillna(0).astype(int)
df['Skill Points Earned'] = df['Skill Points Earned'].fillna(0).astype(int)

# Step 2: Verify the changes
print(df[['Reward Amount', 'Skill Points Earned']].info())
print(df[['Reward Amount', 'Skill Points Earned']].head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8558 entries, 0 to 8557
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Reward Amount        8558 non-null   int32
 1   Skill Points Earned  8558 non-null   int32
dtypes: int32(2)
memory usage: 67.0 KB
None
   Reward Amount  Skill Points Earned
0              0                    0
1              0                    0
2              0                    0
3              0                    0
4              0                    0

In countries column, for the same country name they have been written differenntly like: Iran Islamic Republic of Persian Gulf and Iran, Islamic Republic of Persian Gulf. so i am replace both of them with Iran

In [181]:
# Define a dictionary with variations to standardize
country_replacements = {
    'Iran Islamic Republic of Persian Gulf': 'Iran',
    'Iran, Islamic Republic of Persian Gulf': 'Iran'
}

# Replace the variations in the 'Countries' column
df['Country'] = df['Country'].replace(country_replacements)

# Confirm the replacements
print(df['Country'].value_counts())

Country
United States    3976
India            2836
Nigeria           760
Ghana             275
Pakistan          219
                 ...
France              1
Uzbekistan          1
Somalia             1
Liberia             1
Spain               1
Name: count, Length: 71, dtype: int64

In states column, same state name have been endered in different format like: Abia,Abia state; Adamawa,Adawama state;etc... So i am replacing those with one of the given types among them

In [29]:
# Replace specific State and Country names with 'United States'
#df.loc[(df['State'] == 'Missouri') & (df['Country'] == 'India'), 'Countries'] = 'United States'

In [182]:
# Define the mapping for states
state_mapping = {
    'Abia': ['Abia', 'Abia State'],
    'Abuja': ['Abuja Capital Territory', 'Abuja', 'Abuja FCT', 'Federal Capital Territory', 'FCT', 'Federal capital territor'],
    'Adamawa': ['Adamawa', 'Adamawa State Nigeria'],
    'Akwa Ibom': ['Akwa Ibom', 'Akwa Ibom state'],
    'Andhra Pradesh': ['Andhra Pradesh', 'Andhra pradesh', 'Andhra p', 'Andhra Pradesh state', 'Andhrapradesh', 'Andra pradesh'],
    'Ashanti': ['Ashanti region', 'Ashanti', 'Ashanti Re'],
    'Borno': ['Borno', 'Borno State'],
    'Cross River': ['Cross River', 'Cross River State'],
    'Damietta': ['Damietta', 'dameitta'],
    'Delhi': ['Delhi', 'Del', 'New dehi', 'New Delhi'],
    'Delta': ['Delta', 'Delta State'],
    'Dhaka': ['Dhaka City', 'Dhaka Division', 'dhaka', 'Dhaka North'],
    'Edo': ['Edo', 'Edo State'],
    'Ekiti': ['EKITI', 'Ekiti State', 'Ekito'],
    'Enugu': ['Enugu', 'Enugu state'],
    'FCT': ['FCT'],  # Only for Pakistan
    'Greater Accra': ['Greater Accra', 'Greater Accra Region', 'Greater AccraRegion', 'Greater AccraRegion p', 'Accra'],
    'Gujarat': ['Gujarat', 'gujrat'],
    'Haryana': ['Haryana', 'Haryan', 'Haryans'],
    'Illinois': ['Illinois', 'Illiniois', 'illionis', 'IllINOIS'],
    'Imo': ['Imo', 'Imo state'],
    'Islamabad': ['Islamic Republic of Pakistan', 'Islamic'],
    'Kampala': ['Kampala', 'Kampala city'],
    'Kano': ['Kano', 'Kano State'],
    'Karnataka': ['Karnataka', 'Karnatak', 'Karanataka', 'Karnataka state'],
    'Khyber Pakhtunkhwa': ['Khyber Pakuntunkhwa', 'Khyber Patun'],
    'Kigali': ['Kigali', 'Kigali city'],
    'Kogi': ['Kogi', 'Kogi state'],
    'Kwara': ['Kwara', 'Kwara state'],
    'Lagos': ['Lagos', 'Lagos state'],
    'Madhya Pradesh': ['MADHYA PRADESH', 'Madhya Pradesh', 'M P', 'MP'],
    'Madhesh Pradesh': ['Madhesh Pradesh', 'Madhesh Province'],
    'Maharashtra': ['Maharashtra', 'Maharashtr', 'Maharashtra', 'Maharasthra', 'maharastra', 'maharshtra', 'Mharashthra'],
    'Missouri': ['Missouri', 'MISSOURI', 'Missouri state', 'Missiori', 'Missori', 'missori', 'Missour', 'missuori', 'Missoure', 'missou', 'MissouriMissouru', 'Saint Louis', 'Saint Louis City', 'St Louis'],
    'Nassarawa': ['Nassarawa', 'Nasarawa', 'Nassarawa State'],
    'Niger': ['Niger', 'Niger state'],
    'Northern Region': ['Northern region', 'Northern R', 'Northern'],
    'Ogun': ['Ogun', 'Ogun Stat', 'Ogun State'],
    'Ondo': ['Ondo', 'Ondo state'],
    'Osun': ['Osun', 'Osun State'],
    'Oyo': ['Oyo', 'Oyo N', 'Oyo st', 'Oyo State'],
    'Pakistan': ['Pakistan', 'Pakistan k', 'Pak', 'Pakista', 'pakistan'],
    'Plateau': ['Plateau', 'Plateau state', 'Plateau States'],
    'Punjab': ['Province punjab', 'Pakistan Punjab', 'Punjab', 'PUNJAB', 'punjab'],  # Only for Pakistan
    'Puducherry': ['Pondicherry', 'Puducherry'],
    'Rivers': ['Rivers', 'River State', 'Rivers state', 'RiversState'],
    'Sokoto': ['Sokoto', 'SOKOTO STATE'],
    'Tamil Nadu': ['Tamil Nadu', 'Tamil Nadu state', 'Tamilnadu', 'TN'],
    'Telangana': ['Telangana', 'Tel', 'TELANGAN', 'TELANGANA', 'telangan', 'Telangana', 'Telangana state', 'Telegana', 'Telengana','telengana','telanngana','telangana','Telanagana'],
    'Uttar Pradesh': ['Uttar Pradesh', 'UP', 'UTTAR PRADESH', 'Uttar Prades', 'up', 'uttar pradesh', 'up'],
    'Uttarakhand': ['Uttarakhand', 'Uttrakhand'],
    'West Bengal': ['West Bengal', 'WB', 'WestBengal']
}

# Function to standardize state names based on the country
def standardize_state(row):
    for key, variations in state_mapping.items():
        if row['State'] in variations:
            if row['Country'] == 'Pakistan' and key in ['FCT', 'Punjab']:
                return key
            return key
    return row['State']  # Return original if no match found

# Apply the function to standardize the 'State Name' column
df['State'] = df.apply(standardize_state, axis=1)

# Check the updated DataFrame
print(df[['State', 'Country']])

            State        Country
0        Pakistan       Pakistan
1       Telangana          India
2        Illinois  United States
3        Missouri  United States
4        Missouri  United States
...           ...            ...
8553  Addis Ababa       Ethiopia
8554     Missouri  United States
8555        Lagos        Nigeria
8556     Missouri  United States
8557    Telangana          India

[8558 rows x 2 columns]

In [93]:
df['State'].nunique()

527

In [111]:
df.columns

Index(['Profile Id', 'Learner SignUp DateTime', 'Opportunity Id',
       'Opportunity Name', 'Opportunity Category', 'Opportunity End Date',
       'First Name', 'Last Name', 'Date of Birth', 'Gender', 'Mobile Number',
       'Address Line 1', 'Address Line 2', 'City', 'State', 'Country',
       'Zip Code', 'Institution Name', 'Graduation Date',
       'Current Student Status', 'Current/Intended Major', 'Entry created at',
       'Status Description', 'Status Code', 'Apply Date',
       'Opportunity Start Date', 'Reward Awarded Date', 'Completion Date',
       'Reward Amount', 'Badge Id', 'Badge Name', 'Skill Points Earned',
       'Skills Earned'],
      dtype='object')

here for Hyderabad city some of the country name and state names are wrongly typed ,so just correcting them.

In [94]:
df['City'].nunique()

1341

In [183]:
# Update state and country based on conditions
df.loc[(df['City'] == 'Hyderabad') & (df['Country'] != 'Pakistan'), ['State', 'Country']] = ['Telangana', 'India']

In city column, same city name have been endered in different format like: ADO,Ado Ekiti; Akure,Akure City;etc... So i am replacing those with one of the given types among them

In [184]:
# Define the mapping for cities
city_mapping = {
    'Addis Abeba': ['Addis Abeba', 'addis ababa', 'Addsis Ababa'],
    'ADO': ['ADO', 'Ado Ekiti'],
    'Agbara': ['Agbara', 'Agbara edu'],
    'Ahmedabad': ['Ahmedabad', 'AHEMEDABAD', 'Ahmedabad'],
    'Akure': ['Akure', 'Akure City'],
    'AMBERNATH': ['AMBERNATH', 'Ambarnath'],
    'Anantapur': ['Anantapur', 'Ananthapur'],
    'Ayobo': ['Ayobo', 'Ayoboo'],
    'Ballwin': ['Ballwin', 'Ballwin Manchester'],
    'Bangalore': ['Bangalore', 'Bangalore South', 'Bangalore Urban', 'Banglore'],
    'Bengaluru': ['Bengaluru', 'Bengaluru city', 'Bengaluru Urban'],
    'Benin': ['Benin', 'Benin City'],
    'Bidar': ['Bidar', 'Bida'],
    'Bokaro': ['Bokaro', 'Bokaro Steel City'],
    'Brooklyn': ['Brooklyn'],
    'Can Tho': ['Can Tho', 'Cantho'],
    'Chennai': ['Chennai', 'Chennai Region', 'Chennnai'],
    'Chicago': ['Chicago', 'Chicag'],
    'Delhi': ['Delhi', 'Del', 'New dehi', 'New delhi'],
    'Edo': ['Edo', 'Ede'],  # Ede should be checked if it's correct.
    'Eluru': ['Eluru', 'Eluru city'],
    'FCT': ['FCT', 'Federal Capital Territory'],
    'Greater Noida': ['Greater Noida', 'Greater Noida west'],
    'Gurugram': ['Gurugram', 'Gurgram'],
    'Hanamakonda': ['Hanamakonda', 'Hanumakonda', 'Hanamakonda'],
    'Ho Chi Minh City': ['Ho Chi Minh City', 'Ho'],
    'Hyderabad': ['Hyderabad', 'hyderabad', 'Hyd', 'HYDERABAD', 'hyderbad', 'Hydrabad', 'Hyderbad', 'Hydeabad', 'Hyderaba', 'Hyderabad', 'Hyderavad'],
    'Ibadan': ['Ibadan', 'Iba', 'Ibadan city', 'Ibadan N'],
    'Ifako': ['Ifako', 'Ifako ijaiye'],
    'Ikorodu': ['Ikorodu', 'Ikorodududu'],
    'Isolo': ['Isolo', 'Isolo road'],
    'Jayashankar bhupalapally': ['Jayashankar bhupalapally', 'Jayashankar bhupalapally'],
    'Jimeta': ['Jimeta', 'Jimeta Yola'],
    'Jos city': ['Jos city', 'Jos', 'Jos south'],
    'Kalyan': ['Kalyan', 'Kalyan west'],
    'KANDUKUR': ['KANDUKUR', 'Kandukuru'],
    'Kanpur': ['Kanpur', 'Kanpur Dehat District', 'Kanpur Nagar'],
    'Khairpur': ['Khairpur', 'Khairpur Mirs'],
    'Kigali': ['Kigali', 'Kigali city'],
    'Lagos': ['Lagos', 'Lagos City', 'Lagos s', 'Lagos state'],
    'Lahore': ['Lahore', 'Lahore Pak'],
    'Mandanapalli': ['Mandanapalli', 'Mandanapalle'],
    'Mahbubnagar': ['Mahbubnagar', 'mahabubnagar'],
    'Mandi': ['Mandi', 'Mandi bahauddin'],
    'Mangalore': ['Mangalore', 'Mangaluru'],
    'MARYLAND HEIGHTS': ['MARYLAND HEIGHTS', 'Maryland heights stlouis'],
    'Minna': ['Minna', 'Minne'],
    'missouri': ['missouri'],
    'Mumbai': ['Mumbai', 'Mumbai City', 'Navi mumbai'],
    'Mysore': ['Mysore', 'Mysuru'],
    'Nairobi': ['Nairobi', 'Nairobi Municipality'],
    'Muzaffarnagar': ['Muzaffarnagar', 'MUZAFFARPUR', 'Muzaffarpur'],
    'NANDYAL': ['NANDYAL', 'NANDYAL KURNOOL'],
    'Narasaraopeta': ['Narasaraopeta', 'Narasaraopet'],
    'New Dameitta': ['New Dameitta', 'new dameitta'],
    'New Okooba': ['New Okooba', 'New oko oba'],
    'Nizamabad': ['Nizamabad', 'Nizamabad District'],
    'Obuase': ['Obuase', 'Obuasi'],
    'Ondo': ['Ondo', 'Ondo city'],
    'Owerri': ['Owerri', 'Owerri municipal'],
    'Pakistan': ['Pakistan', 'Pakistam'],
    'Patan': ['Patan'],
    'Port Harcourt': ['Port Harcourt', 'Port Harcourt city', 'Portharcourt'],
    'Rajampeta': ['Rajampeta', 'Rajampet'],
    'Roorke': ['Roorke', 'roorkee'],
    'Saint Louis': ['Saint Louis', 'saint lo', 'Saint Louis c', 'Saint Louis city', 'Saint Louis I',
                    'Saint Louis university', 'Saint Louise', 'saint lousis', 'Saintloui', 'Saintlouis', 'Saintt Louis',
                    'SAIT LOUIS', 'sanit louis', 'St', 'St Loius', 'St louis', 'St Louis City', 'stl', 'stLouis'
                   'SAINT LOUIS','St Louis'],
    'St charles': ['St charles', 'StCharles', 'St Charles'],
    'Sathupally': ['Sathupally', 'Sathupalli'],
    'Sattenapalli': ['Sattenapalli', 'SATTENAPALLE', 'Sattenpalli'],
    'Sharjah': ['Sharjah', 'Sharjha'],
    'Sheikhupura': ['Sheikhupura', 'Sheikupura'],
    'Sonipat': ['Sonipat', 'sonepat'],
    'Tarkwa': ['Tarkwa', 'Tarkwa Tamso'],
    'Thane': ['Thane', 'THANE WEST'],
    'Tirupathi': ['Tirupathi', 'Tirupati'],
    'VISHAKHAPATANAM': ['VISHAKHAPATANAM', 'Visakhapatnam', 'Vishakhapatnam'],
    'Vissanapet': ['Vissanapet', 'vissannapeta'],
    'warangal': ['warangal', 'waranagal', 'Warangal urban', 'Warangal rural'],
    'Zaria': ['Zaria', 'Zaria City']
}

# Function to standardize city names based on the country
def standardize_city(row):
    for key, variations in city_mapping.items():
        if row['City'] in variations:
            if row['City'] == 'Hyderabad' and row['Country'] != 'Pakistan':
                # Change the state name and country if city is Hyderabad
                row['State'] = 'Telangana'
                row['Country'] = 'India'
            return key  # Return the standardized city name
    return row['City']  # Return original if no match found

# Apply the function to standardize the 'City Name' column
df['City'] = df.apply(standardize_city, axis=1)

# Check the updated DataFrame
print(df[['City', 'Country']])

             City        Country
0        Peshawar       Pakistan
1       vikarabad          India
2         Chicago  United States
3     Saint Louis  United States
4     Saint Louis  United States
...           ...            ...
8553  Addis Ababa       Ethiopia
8554  SAINT LOUIS  United States
8555       Kosofe        Nigeria
8556  Saint Louis  United States
8557  Hanamakonda          India

[8558 rows x 2 columns]

In [185]:
# City mapping dictionary with all variations
city_mapping = {
    'Addis Ababa': ['Addis Abeba', 'addis ababa', 'Addsis Ababa'],
    'Ado Ekiti': ['ADO', 'Ado Ekiti'],
    'Agbara': ['Agbara', 'Agbara edu'],
    'Ahmedabad': ['AHEMEDABAD', 'Ahmedabad','Ahemedabad'],
    'Akure': ['Akure', 'Akure City'],
    'Ambarnath': ['AMBERNATH', 'Ambarnath'],
    'Anantapur': ['Ananthapur', 'Anantapur'],
    'Ayobo': ['Ayobo', 'Ayoboo'],'Ballwin': ['Ballwin', 'Ballwin Manchester'],
    'Bangalore': ['Bangalore', 'Bangalore South', 'Bangalore Urban', 'Banglore',
                  'Bengaluru', 'Bengaluru city', 'Bengaluru Urban','Bengaluru'],
    'Benin': ['Benin', 'Benin City'],
    'Bidar': ['Bidar', 'Bida'],
    'Bokaro': ['Bokaro', 'Bokaro Steel City'],
    'Brooklyn': ['Brooklyn'],
    'Can Tho': ['Can Tho', 'Cantho'],
    'Chennai': ['Chennai', 'Chennai Region', 'Chennnai'],
    'Chicago': ['Chicago', 'Chicag'],
    'Delhi': ['Delhi', 'Del', 'New dehi', 'New delhi'],
    'Edo': ['Edo', 'Ede'],
    'Eluru': ['Eluru', 'Eluru city'],
    'FCT': ['FCT', 'Federal Capital Territory'],
    'Greater Noida': ['Greater Noida', 'Greater Noida west'],
    'Gurugram': ['Gurugram', 'Gurgram'],
    'Hanamakonda': ['Hanamakonda', 'Hanumakonda', 'Hanamakonda'],
    'Ho Chi Minh City': ['Ho Chi Minh City', 'Ho'],
    'Hyderabad': ['Hyderabad', 'hyderabad', 'Hyd', 'HYDERABAD', 'hyderbad', 'Hydrabad', 'Hyderbad', 'Hydeabad', 'Hyderaba', 'Hyderabad', 'Hyderavad'],
    'Ibadan': ['Ibadan', 'Iba', 'Ibadan city', 'Ibadan N'],
    'Ifako Ijaiye': ['Ifako', 'Ifako ijaiye'],
    'Ikorodu': ['Ikorodu', 'Ikorodududu'],
    'Isolo': ['Isolo', 'Isolo road'],
    'Jayashankar Bhupalapally': ['Jayashankar bhupalapally', 'Jayashankar bhupalpally'],
    'Jimeta': ['Jimeta', 'Jimeta Yola'],
    'Jos': ['Jos city', 'Jos', 'Jos south'],
    'Kalyan': ['Kalyan', 'Kalyan west'],
    'Kandukuru': ['KANDUKUR', 'Kandukur'],
    'Kanpur': ['Kanpur', 'Kanpur Dehat District', 'Kanpur Nagar'],
    'Khairpur': ['Khairpur', 'Khairpur Mirs'],
    'Kigali': ['Kigali', 'Kigali city'],
    'Lagos': ['Lagos', 'Lagos City', 'Lagos s', 'Lagos state'],
    'Lahore': ['Lahore', 'Lahore Pak'],
    'Mandanapalli': ['Mandanapalli', 'Mandanapalle'],
    'Mahbubnagar': ['Mahbubnagar', 'mahabubnagar'],
    'Mandi': ['Mandi', 'Mandi bahauddin'],
    'Mangalore': ['Mangalore', 'Mangaluru'],
    'Maryland Heights': ['MARYLAND HEIGHTS', 'Maryland heights stlouis'],
    'Minna': ['Minna', 'Minne'],
    'Missouri': ['missouri'],
    'Mumbai': ['Mumbai', 'Mumbai City', 'Navi mumbai'],
    'Mysore': ['Mysore', 'Mysuru'],
    'Nairobi': ['Nairobi', 'Nairobi Municipality'],
    'Muzaffarpur': ['Muzaffarnagar', 'MUZAFFARPUR', 'Muzaffarpur'],
    'Nandyal': ['NANDYAL', 'NANDYAL KURNOOL'],
    'Narasaraopeta': ['Narasaraopeta', 'Narasaraopet'],
    'New Dameitta': ['New Dameitta', 'new dameitta'],
    'New Okooba': ['New Okooba', 'New oko oba'],
    'Nizamabad': ['Nizamabad', 'Nizamabad District'],
    'Obuasi': ['Obuase', 'Obuasi'],
    'Ondo': ['Ondo', 'Ondo city'],
    'Owerri': ['Owerri', 'Owerri municipal'],
    'Pakistan': ['Pakistan', 'Pakistam'],
    'Patan': ['Patan'],
    'Port Harcourt': ['Port Harcourt', 'Port Harcourt city', 'Portharcourt'],
    'Rajampeta': ['Rajampeta', 'Rajampet'],
    'Roorkee': ['Roorke', 'roorkee'],
    'Saint Louis': ['Saint Louis', 'saint lo', 'Saint Louis c','SAINT LOUIS','St Louis', 'Saint Louis city', 'Saint Louis I', 'Saint Louis university', 'Saint Louise', 'saint lousis', 'Saintloui', 'Saintlouis', 'Saintt Louis', 'SAINT LOUIS', 'sainthood', 'St', 'St Loius', 'St louis', 'St Louis City', 'stl', 'stLouis'],
    'St Charles': ['St charles', 'StCharles', 'St Charles'],
    'Sathupally': ['Sathupally', 'Sathupalli'],
    'Sattenapalli': ['Sattenapalli', 'SATTENAPALLE', 'Sattenpalli'],
    'Sharjah': ['Sharjah', 'Sharjha'],
    'Sheikhupura': ['Sheikhupura', 'Sheikupura'],
    'Sonipat': ['Sonipat', 'sonepat'],
    'Tarkwa': ['Tarkwa', 'Tarkwa Tamso'],
    'Thane': ['Thane', 'THANE WEST'],
    'Tirupati': ['Tirupathi', 'Tirupati'],
    'Visakhapatnam': ['VISHAKHAPATANAM', 'Visakhapatnam', 'Vishakhapatnam'],
    'Vissanapet': ['Vissanapet', 'vissannapeta'],
    'Warangal': ['warangal', 'waranagal', 'Warangal urban', 'Warangal rural'],
    'Zaria': ['Zaria', 'Zaria City']
}

# Create a reverse mapping for easy lookup
reverse_mapping = {}
for standard, variations in city_mapping.items():
    for variation in variations:
        reverse_mapping[variation.strip().lower()] = standard

# Function to map city names
def map_city(row):
    city_lower = row['City'].strip().lower()
    if city_lower in reverse_mapping:
        return reverse_mapping[city_lower]
    return row['City']

# Apply the mapping
df['City'] = df.apply(map_city, axis=1)

# Updating the state and country based on the city
df.loc[(df['City'] == 'Hyderabad') & (df['Country'] != 'Pakistan'), 'Country'] = 'India'
df.loc[(df['City'] == 'Hyderabad') & (df['Country'] != 'Pakistan'), 'State'] = 'Telangana'

# Display the updated DataFrame
print(df)

                                Profile Id Learner SignUp DateTime  \
0     004b8a25-17d4-4e9a-a41b-b5336327e170              2023-06-14
1     00628747-9775-4a85-a179-4d5007ccb8b7              2023-05-01
2     00841155-6c62-4f83-b165-57ba0df9c031              2023-04-09
3     00f5161c-ba85-472d-9b0a-3301aac78598              2023-08-29
4     01273a5e-fcc5-4b1a-a637-19aff497dac1              2023-01-06
...                                    ...                     ...
8553  f9f62826-54ba-4911-8b72-226bda509ad8              2024-03-05
8554  fbc5c29d-4bfe-4056-adb9-a91e0f537b74              2024-03-06
8555  fc54550e-fb48-41f8-8e9d-f224868edfa5              2024-02-29
8556  fe592afe-3d80-41d4-abcd-ce2c943e7b2f              2023-12-23
8557  fecf5e0c-5403-4fb7-ba5c-55b041208514              2023-06-01

                      Opportunity Id  \
0     00000000-0GN2-A0AY-7XK8-C5FZPP
1     00000000-0GN2-A0AY-7XK8-C5FZPP
2     00000000-0GN2-A0AY-7XK8-C5FZPP
3     00000000-0GN2-A0AY-7XK8-C5FZPP
4     00000000-0GN2-A0AY-7XK8-C5FZPP
...                              ...
8553  00000000-10GQ-RJHT-3G4S-BKGBY1
8554  00000000-10GQ-RJHT-3G4S-BKGBY1
8555  00000000-10GQ-RJHT-3G4S-BKGBY1
8556  00000000-10GQ-RJHT-3G4S-BKGBY1
8557  00000000-10GQ-RJHT-3G4S-BKGBY1

                                       Opportunity Name Opportunity Category  \
0     Career Essentials: Getting Started with Your P...               Course
1     Career Essentials: Getting Started with Your P...               Course
2     Career Essentials: Getting Started with Your P...               Course
3     Career Essentials: Getting Started with Your P...               Course
4     Career Essentials: Getting Started with Your P...               Course
...                                                 ...                  ...
8553                         Freelance Mastery workshop                Event
8554                         Freelance Mastery workshop                Event
8555                         Freelance Mastery workshop                Event
8556                         Freelance Mastery workshop                Event
8557                         Freelance Mastery workshop                Event

     Opportunity End Date        First Name   Last Name Date of Birth  Gender  \
0              2024-06-29             Faria        Khan    2001-01-12  Female
1              2024-06-29          Poojitha     Bembadi    2000-08-16  Female
2              2024-06-29          Emmanuel    Thompson    2002-01-27    Male
3              2024-06-29  Amrutha Varshini   Anagurthi    1999-11-01  Female
4              2024-06-29    Vinay Varshith    Pechetti    2000-04-19    Male
...                   ...               ...         ...           ...     ...
8553           2024-03-08             Selam      Endale    2006-10-14  Female
8554           2024-03-08     Gowri Sailesh   Kotipalli    1999-05-18    Male
8555           2024-03-08            Abiola     Ibrahim    1999-03-16    Male
8556           2024-03-08       venumadhavi   bogireddy    1997-06-05  Female
8557           2024-03-08   Prashanth Reddy  Varanganti    2000-11-30    Male

      ... Status Code  Apply Date Opportunity Start Date Reward Awarded Date  \
0     ...        1080  2023-06-14             2022-11-03          1900-01-01
1     ...        1080  2023-05-01             2022-11-03          1900-01-01
2     ...        1080  2023-05-11             2022-11-03          1900-01-01
3     ...        1070  2023-10-09             2022-11-03          1900-01-01
4     ...        1080  2023-01-06             2022-11-03          1900-01-01
...   ...         ...         ...                    ...                 ...
8553  ...        1070  2024-03-05             2024-03-08          1900-01-01
8554  ...        1070  2024-03-06             2024-03-08          1900-01-01
8555  ...        1070  2024-02-29             2024-03-08          1900-01-01
8556  ...        1070  2024-02-27             2024-03-08          1900-01-01
8557  ...        1070  2024-02-16             2024-03-08          1900-01-01

     Completion Date Reward Amount Badge Id Badge Name Skill Points Earned  \
0         1900-01-01             0      NaN        NaN                   0
1         1900-01-01             0      NaN        NaN                   0
2         1900-01-01             0      NaN        NaN                   0
3         1900-01-01             0      NaN        NaN                   0
4         1900-01-01             0      NaN        NaN                   0
...              ...           ...      ...        ...                 ...
8553      1900-01-01             0      NaN        NaN                   0
8554      1900-01-01             0      NaN        NaN                   0
8555      1900-01-01             0      NaN        NaN                   0
8556      1900-01-01             0      NaN        NaN                   0
8557      1900-01-01             0      NaN        NaN                   0

     Skills Earned
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
...            ...
8553           NaN
8554           NaN
8555           NaN
8556           NaN
8557           NaN

[8558 rows x 33 columns]

In [98]:
df['City'].nunique()

1156

In [123]:
df['City'].head(30)

0        Peshawar
1       vikarabad
2         Chicago
3     Saint Louis
4     Saint Louis
5          Rajkot
6          Mumbai
7           Dubai
8          Meerut
9         Aligarh
10        Jalingo
11       Alimosho
12    Saint Louis
13     Alexandria
14      kathmandu
15       Bathinda
16        Cordova
17       Tirupati
18         Suleja
19        Nairobi
20        Katsina
21    Saint Louis
22         Pedana
23      Bengaluru
24      Hyderabad
25    Saint Louis
26        Ile Ife
27    Saint Louis
28      Maiduguri
29     Gujranwala
Name: City, dtype: object

For zipcodes column if Country is Ghana, then if the values are numbers then replace them with 233, else if they are alphabets/alphanumeric/characters present then extract first 3/2 alphabets only, if there are 3 alphabets in the beginning extract those 3 else extract first 2 character and place them in that column.
if it is alpha numeric like numeric followed by space or alphabet then removt those space and alphabets and only take numbers.

In [186]:
# Function to process the 'Zipcode' column based on country
def process_zipcode(row):
    if row['Country'].strip().lower() == 'ghana':
        zipcode = str(row['Zip Code']).strip()
        # Check if the value is numeric
        if zipcode.isnumeric():
            return '233'
        else:
            # Extract first 3 characters if all are alphabets
            if zipcode[:3].isalpha():
                return zipcode[:3].upper()
            # Extract first 2 characters otherwise
            else:
                return zipcode[:2].upper()
    return row['Zip Code']  # Keep the original value if not Ghana

# Apply the function to the 'Zipcode' column
df['Zip Code'] = df.apply(process_zipcode, axis=1)

# Display the updated DataFrame
print(df)

                                Profile Id Learner SignUp DateTime  \
0     004b8a25-17d4-4e9a-a41b-b5336327e170              2023-06-14
1     00628747-9775-4a85-a179-4d5007ccb8b7              2023-05-01
2     00841155-6c62-4f83-b165-57ba0df9c031              2023-04-09
3     00f5161c-ba85-472d-9b0a-3301aac78598              2023-08-29
4     01273a5e-fcc5-4b1a-a637-19aff497dac1              2023-01-06
...                                    ...                     ...
8553  f9f62826-54ba-4911-8b72-226bda509ad8              2024-03-05
8554  fbc5c29d-4bfe-4056-adb9-a91e0f537b74              2024-03-06
8555  fc54550e-fb48-41f8-8e9d-f224868edfa5              2024-02-29
8556  fe592afe-3d80-41d4-abcd-ce2c943e7b2f              2023-12-23
8557  fecf5e0c-5403-4fb7-ba5c-55b041208514              2023-06-01

                      Opportunity Id  \
0     00000000-0GN2-A0AY-7XK8-C5FZPP
1     00000000-0GN2-A0AY-7XK8-C5FZPP
2     00000000-0GN2-A0AY-7XK8-C5FZPP
3     00000000-0GN2-A0AY-7XK8-C5FZPP
4     00000000-0GN2-A0AY-7XK8-C5FZPP
...                              ...
8553  00000000-10GQ-RJHT-3G4S-BKGBY1
8554  00000000-10GQ-RJHT-3G4S-BKGBY1
8555  00000000-10GQ-RJHT-3G4S-BKGBY1
8556  00000000-10GQ-RJHT-3G4S-BKGBY1
8557  00000000-10GQ-RJHT-3G4S-BKGBY1

                                       Opportunity Name Opportunity Category  \
0     Career Essentials: Getting Started with Your P...               Course
1     Career Essentials: Getting Started with Your P...               Course
2     Career Essentials: Getting Started with Your P...               Course
3     Career Essentials: Getting Started with Your P...               Course
4     Career Essentials: Getting Started with Your P...               Course
...                                                 ...                  ...
8553                         Freelance Mastery workshop                Event
8554                         Freelance Mastery workshop                Event
8555                         Freelance Mastery workshop                Event
8556                         Freelance Mastery workshop                Event
8557                         Freelance Mastery workshop                Event

     Opportunity End Date        First Name   Last Name Date of Birth  Gender  \
0              2024-06-29             Faria        Khan    2001-01-12  Female
1              2024-06-29          Poojitha     Bembadi    2000-08-16  Female
2              2024-06-29          Emmanuel    Thompson    2002-01-27    Male
3              2024-06-29  Amrutha Varshini   Anagurthi    1999-11-01  Female
4              2024-06-29    Vinay Varshith    Pechetti    2000-04-19    Male
...                   ...               ...         ...           ...     ...
8553           2024-03-08             Selam      Endale    2006-10-14  Female
8554           2024-03-08     Gowri Sailesh   Kotipalli    1999-05-18    Male
8555           2024-03-08            Abiola     Ibrahim    1999-03-16    Male
8556           2024-03-08       venumadhavi   bogireddy    1997-06-05  Female
8557           2024-03-08   Prashanth Reddy  Varanganti    2000-11-30    Male

      ... Status Code  Apply Date Opportunity Start Date Reward Awarded Date  \
0     ...        1080  2023-06-14             2022-11-03          1900-01-01
1     ...        1080  2023-05-01             2022-11-03          1900-01-01
2     ...        1080  2023-05-11             2022-11-03          1900-01-01
3     ...        1070  2023-10-09             2022-11-03          1900-01-01
4     ...        1080  2023-01-06             2022-11-03          1900-01-01
...   ...         ...         ...                    ...                 ...
8553  ...        1070  2024-03-05             2024-03-08          1900-01-01
8554  ...        1070  2024-03-06             2024-03-08          1900-01-01
8555  ...        1070  2024-02-29             2024-03-08          1900-01-01
8556  ...        1070  2024-02-27             2024-03-08          1900-01-01
8557  ...        1070  2024-02-16             2024-03-08          1900-01-01

     Completion Date Reward Amount Badge Id Badge Name Skill Points Earned  \
0         1900-01-01             0      NaN        NaN                   0
1         1900-01-01             0      NaN        NaN                   0
2         1900-01-01             0      NaN        NaN                   0
3         1900-01-01             0      NaN        NaN                   0
4         1900-01-01             0      NaN        NaN                   0
...              ...           ...      ...        ...                 ...
8553      1900-01-01             0      NaN        NaN                   0
8554      1900-01-01             0      NaN        NaN                   0
8555      1900-01-01             0      NaN        NaN                   0
8556      1900-01-01             0      NaN        NaN                   0
8557      1900-01-01             0      NaN        NaN                   0

     Skills Earned
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
...            ...
8553           NaN
8554           NaN
8555           NaN
8556           NaN
8557           NaN

[8558 rows x 33 columns]

now if in zip column if the values are in the format 60614-4904 then only consider 60614 from it.
if they are in this format 485 garki then only take 485 from it.
if they are in the format Saifali1163 or WA189932 or Po box 10410 or MO 63108 then only take 1163 or 189932 or 10410 10410 from it.
if there are any spaces in between like this 625 020 or 600 127 or LS7 2RQ, then remove the space and consider it as 625020 or 600127 or LS72RQ.
Else let them be as they are

In [187]:
import re
# Function to process the 'Zipcode' column
def process_zipcode(row):
    zipcode = str(row['Zip Code']).strip()
    
    # Case 1: Format 60614-4904 -> Take first part before '-'
    if '-' in zipcode:
        return zipcode.split('-')[0]
    
    # Case 2: Format "485 garki" -> Extract numeric part only
    elif re.match(r'^\d+\s*\D+', zipcode):
        return re.findall(r'^\d+', zipcode)[0]
    
    # Case 3: Format like "Saifali1163", "WA189932", "Po box 10410", "MO 63108"
    elif re.search(r'\d+', zipcode):
        return re.findall(r'\d+', zipcode)[-1]
    
    # Case 4: If spaces between numeric values, e.g., 625 020 -> Remove spaces
    elif re.match(r'^\d+\s+\d+$', zipcode):
        return zipcode.replace(' ', '')
    
    # Default: Leave as-is
    return zipcode

# Apply the function to the 'Zipcode' column
df['Zip Code'] = df.apply(process_zipcode, axis=1)

# Display the updated DataFrame
print(df)

                                Profile Id Learner SignUp DateTime  \
0     004b8a25-17d4-4e9a-a41b-b5336327e170              2023-06-14
1     00628747-9775-4a85-a179-4d5007ccb8b7              2023-05-01
2     00841155-6c62-4f83-b165-57ba0df9c031              2023-04-09
3     00f5161c-ba85-472d-9b0a-3301aac78598              2023-08-29
4     01273a5e-fcc5-4b1a-a637-19aff497dac1              2023-01-06
...                                    ...                     ...
8553  f9f62826-54ba-4911-8b72-226bda509ad8              2024-03-05
8554  fbc5c29d-4bfe-4056-adb9-a91e0f537b74              2024-03-06
8555  fc54550e-fb48-41f8-8e9d-f224868edfa5              2024-02-29
8556  fe592afe-3d80-41d4-abcd-ce2c943e7b2f              2023-12-23
8557  fecf5e0c-5403-4fb7-ba5c-55b041208514              2023-06-01

                      Opportunity Id  \
0     00000000-0GN2-A0AY-7XK8-C5FZPP
1     00000000-0GN2-A0AY-7XK8-C5FZPP
2     00000000-0GN2-A0AY-7XK8-C5FZPP
3     00000000-0GN2-A0AY-7XK8-C5FZPP
4     00000000-0GN2-A0AY-7XK8-C5FZPP
...                              ...
8553  00000000-10GQ-RJHT-3G4S-BKGBY1
8554  00000000-10GQ-RJHT-3G4S-BKGBY1
8555  00000000-10GQ-RJHT-3G4S-BKGBY1
8556  00000000-10GQ-RJHT-3G4S-BKGBY1
8557  00000000-10GQ-RJHT-3G4S-BKGBY1

                                       Opportunity Name Opportunity Category  \
0     Career Essentials: Getting Started with Your P...               Course
1     Career Essentials: Getting Started with Your P...               Course
2     Career Essentials: Getting Started with Your P...               Course
3     Career Essentials: Getting Started with Your P...               Course
4     Career Essentials: Getting Started with Your P...               Course
...                                                 ...                  ...
8553                         Freelance Mastery workshop                Event
8554                         Freelance Mastery workshop                Event
8555                         Freelance Mastery workshop                Event
8556                         Freelance Mastery workshop                Event
8557                         Freelance Mastery workshop                Event

     Opportunity End Date        First Name   Last Name Date of Birth  Gender  \
0              2024-06-29             Faria        Khan    2001-01-12  Female
1              2024-06-29          Poojitha     Bembadi    2000-08-16  Female
2              2024-06-29          Emmanuel    Thompson    2002-01-27    Male
3              2024-06-29  Amrutha Varshini   Anagurthi    1999-11-01  Female
4              2024-06-29    Vinay Varshith    Pechetti    2000-04-19    Male
...                   ...               ...         ...           ...     ...
8553           2024-03-08             Selam      Endale    2006-10-14  Female
8554           2024-03-08     Gowri Sailesh   Kotipalli    1999-05-18    Male
8555           2024-03-08            Abiola     Ibrahim    1999-03-16    Male
8556           2024-03-08       venumadhavi   bogireddy    1997-06-05  Female
8557           2024-03-08   Prashanth Reddy  Varanganti    2000-11-30    Male

      ... Status Code  Apply Date Opportunity Start Date Reward Awarded Date  \
0     ...        1080  2023-06-14             2022-11-03          1900-01-01
1     ...        1080  2023-05-01             2022-11-03          1900-01-01
2     ...        1080  2023-05-11             2022-11-03          1900-01-01
3     ...        1070  2023-10-09             2022-11-03          1900-01-01
4     ...        1080  2023-01-06             2022-11-03          1900-01-01
...   ...         ...         ...                    ...                 ...
8553  ...        1070  2024-03-05             2024-03-08          1900-01-01
8554  ...        1070  2024-03-06             2024-03-08          1900-01-01
8555  ...        1070  2024-02-29             2024-03-08          1900-01-01
8556  ...        1070  2024-02-27             2024-03-08          1900-01-01
8557  ...        1070  2024-02-16             2024-03-08          1900-01-01

     Completion Date Reward Amount Badge Id Badge Name Skill Points Earned  \
0         1900-01-01             0      NaN        NaN                   0
1         1900-01-01             0      NaN        NaN                   0
2         1900-01-01             0      NaN        NaN                   0
3         1900-01-01             0      NaN        NaN                   0
4         1900-01-01             0      NaN        NaN                   0
...              ...           ...      ...        ...                 ...
8553      1900-01-01             0      NaN        NaN                   0
8554      1900-01-01             0      NaN        NaN                   0
8555      1900-01-01             0      NaN        NaN                   0
8556      1900-01-01             0      NaN        NaN                   0
8557      1900-01-01             0      NaN        NaN                   0

     Skills Earned
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
...            ...
8553           NaN
8554           NaN
8555           NaN
8556           NaN
8557           NaN

[8558 rows x 33 columns]

In [101]:
df['Institution Name'].nunique()

2089

In [188]:
# Institution Mapping Dictionary
institution_mapping = {
    "Abdul Wali Khan University": ["Abdul wali khan University Mardan"],
    "Abia State University": ["Abia state university  uturu.", "Abia State UNIVERSITY  UTURU",
                             "Abia state university uturu.", "Abia State UNIVERSITY UTURU"
                             ],
    "Addis Ababa University": [
        "Addis Ababa Science and Technology University", 
        "ADDIS ABABA INSTITUTE OF TECHNOLOGY"
    ],
    "Accra Technical university":["Accra Institute of Technology"],
    
    'ADDIS ABABA INSTITUTE OF TECHNOLOGY': [
        'Addis Ababa Science and Technology University',
        'Addis Ababa University'
    ],
    'Adekunle Ajasin University': [
        'Adekunle Ajasin University  Akungba Akoko',
        'Adekunle Ajasin University  Akungba Ondo  Nigeria',
        'Adeleke university',
    ],
    'African School of Management and Technology': [
        'African School of Management and Technologie',
        'African School of Management of technology'
        
    ],
    "ABC":["ABC INTER COLLEGE"],
    
    'Ahmadu Bello University': [
        'Ahmadu Bello University  zaria',
        'Ahmadu Bello University Zaria Kaduna State',
        'Ahmadu Bello university Zaria kaduna state Nigeria'
        'Ahmadu Bello university Zaria',
        'Ahmadu Bello university zaria'
        'Ahmadu Bello University Zaria  Nigeria.'
    ],
    'Allama Iqbal Open University': [
        'allama iqbal Open university','allama iqbal open universty',
        'Allama iqbal open university','allama iqbal open universty',
        'Allama Iqbal university'
    ],
    "Al-Nahrain University":['al-nahrain',
                             'Al-Nahrain University',
                             'AI-Nahrain University',
                             'aI-nahrain'],
    
    'Ambalika Institute of Management and Technology': [
        'Ambalika institue of management and technology'
    ],
    'Ambrose Alli University': [
        'Ambrose Alli University Ekpoma'
    ],
    'Amity University': [
        'Amity University Online'
    ],
    'Amrita Vishwa Vidyapeetham': [
        'Amrita Vishwa Vidyapeetham  Kerala',
        'Amrita Vishwa Vidyapeetham Kerala'
        'Amrita vishwa vishyapeetham','Amrita Vishwa Vidyapeetham'
    ],
    'Ananthalakshmi Institute of Technology and Sciences': [
        'ANANTHA LAKSHMI INSTITUTE OF TECHNOLOGY AND SCIENCES'
    ],
    'Anurag group of institutions': [
        'Anurag College of engineering',
        'Anurag university',
        'Anurag University'
    ],
    'Ashoka Academy': [
        'Ashoka'
    ],
    'Babcock University': [
        'BABCOCK'
    ],
    'Bahria University': [
        'Bahria University Karachi Campus','Bahria University Karachi Campus'
    ],
    'Beaconhouse': [
        'Beacon House',
        'Beaconhouse College Programme Gulberg',
        'Beaconhouse Juniper Campus',
        'Beaconhouse Margalla campus H-8 Islamabad',
        'Beaconhouse School System'
    ],
    'Bharath University': [
        'bharath university',
        'Bharath Institute of Higher Education And Research'
    ],
    'Bharati Vidyapeeth College of Engineering': [
        'Bharati Vidyapeeth deemed to be university',
        'Bharati Vidyapeeth College of Engineering Lavale Pune' 
    ],
    'Bingham University': [
        'Bingham University Karu',
        'Bingham University Karu Nassarawa state Nigeria'
    ],
    'BITS Pilani Hyderabad Campus': [
        'Birla Institute of Technology',
        'Birla institute of technology Mesra',
        'Birla Institute of Technology and Science Pilani'
    ],

    'Camellia Institute of Engineering and Technology': [
        'Camellia School of Engineering and Technology'
    ],
    'Christian Service University College': [
        'Christian service university college of university of Ghana'
    ],
    'CMR Institute of Technology': [
        'cmr','CMR Technical Campus','Cmr Institute of technology',
        'CMR college of engineering and technology',
        'CMR Engineering College',
        'Cmr Institute of technology',
        'cmr instutie of technology',
        'CMR Technical Campus',
        'CMR College of Pharmacy',
        'CMRit','CMR ENGINEERING COLLEGE','CMR INSTITUTE OF TECHNOLOGY',
        'CMR INSTITUTE OF TECHNOLOGY HYDERABAD',
    ],
        "COMSATS":[
        'Comsats University Islamabad','Comstas university Islamabad attock campus',
        'Comsats university Islamabad attock campus','COMSATS university Islamabad campus',
        'COMSATS university Islamabad campus',
        'Comstas university Islamabad attock campus'
    ],
    'Creighton University': [
        'Creighton Preparatory School',
        'Criegton University'
    ],
   
    'DAV Public School': [
        'DAV School  Bhahua',
    ],
    'DAV Boys Sr. Sec. School': [
        'DAV BOYS SENIOR SECONDARY SCHOOL',
        'D A V Boys Senior Secondary School  Gopalapuram'
    ],
    'Deen dayal upadhyaya college University of Delhi':[
        'Deen dayal upadhyaya college University of Delhi',
        'Deen dayal upadhyaya college University of Delhi'
        'Deen Dayal Upadhyaya Gorakhpur University',
        'Deen Dayal upadhyaya college University of Delhi',
        'DEEN DAYAL UPADHYAYA GORAKHPUR UNIVERSITY',
    ],
    'Delhi University': [
        'Delhi Technological University'
    ],
    'Delta State University': [
        'Delta state polytechnic',
        'Delta state University  Abraka',
        'Delta state University Abraka'
    ],
    'Dhaka University': [
        'Dhaka city College'
    ],
    'Dhanalakshmi Srinivasan Engineering College': [
        'Dhanalakshmi Srinivasan Engineering College Perambalur',
        'Dhanalakshmi Srinivasan Engineering Collge'
    ],
    'Doon University': [
        'Doon Public School'
    ],
    'Dr. B.R. Ambedkar National Institute of Technology Jalandhar': [
        'Dr Bhimrao Ambedkar University',
        'Dr BR AMBEDKAR NATIONAL INSTITUTE OF TECHNOLOGY JALANDHAR',
        'DR BR AMBEDKAR NATIONAL INSTITUTE OF TECHNOLOGY JALANDHAR',
        'Dr. B.R. Ambedkar National Institute of Technology Jalandhar'
    ],
    'Dr. D.Y. Patil College of Engineering and Innovation Pune': [
        'Dr D.Y. Patil College of Engineering and Innovation',
        'Dr DY Patil College of Engineering and Innovation',
        'Dr DY PATIL SCHHOL OF SCIENCE AND TECHNOLOGY',
        'DR.D Y PATIL SCHOOL OF SCIENCE AND TECHNOLOGY',
        'Dr.D.Y.Patil school of science and technology pune',
        'Dr. D.Y. Patil College of Engineering and Innovation Pune',
        'dy patil college of engineering',
        'DY Patil School of Science and Technology',
        'Dr D Y patil College of engineering and innovation pune',
        'Dr D Y patil college of engineering and innovation pune'
        'DY Patil College of Engineering and Innovation'
    ],
    'Dwarkadas J Sanghvi College of Engineering': [
        'Dwarkadas J. Sanghvi college of Engineering'
    ],
    
    "Egerton University": ["Egerton University niversity"],
    "Ekiti State University": ["Ekiti State University Ado Ekiti"],
    "Enugu State University": ["Enugu State University of Science and Technology",
                               "Enugu State University of Science and technology"
                              ],
    "FAST NUCES": ["FAST -NUCES"],
    "Federal Polytechnic Ado Ekiti": ["Federal Polytechnic Ado Ekiti. Ekiti state Nigeria"],
    "Federal University of Agriculture Makurdi": [
        "Federal University of Agriculture  Makurdi", 
        "Federal University of Agriculture Makurdi Benue State"
    ],

    "Federal University of Petroleum Resources": [
        "Federal university of Petroleum resource effurun delta state",
        "Federal university of petroleum resource effurun delta state",
        "Federal University of Petroleum Resources  Effurun", 
        "Federal University of Petroleum Resources Effurun",
        "Federal University of Petroleum Resource",
        #"Federal university of petroleum university",
    ],
    
    "Federal University of Agriculture Makurdi": [
        "Federal University of Agriculture Markurdi", 
        "Federal University of Agriculture  Makurdi", 
        "Federal University of Agriculture Makurdi Benue State"
    ],
    "Federal University of Technology Owerri": [
        "Federal University of Technology Owerri",
        "Federal University of Technology Owerri Nigeria",
        "Federal University of Technology Owerri Nigeria",
        "Federal University of Technology  Owerri", 
        "Federal University of Technology Owerri  Imo Nigeria",
        "Federal University of Technology Owerri Imo Nigeria"
    ],
    "Federal University of Technology Akure": [
        "Federal University of Technology  Akure Nigeria"
    ],
    "Federal University Oye Ekiti": [
        "Federal university oye ekiti.", 
        "Federal University Oye-Ekiti Ekiti"
    ],
    "Federal University Wukari": [
        "Federal university wukari", 
        "Federal University Wukari  Taraba", 
        "Federal University Wukari Taraba",
        "Federal University Wukari Taraba state Nigeria"
    ],
    "Francis Howell": [
        "Francis Howell High School", 
        "Francis Howell North High School"
    ],
    "Gayatri Vidya Parishad college of engineering": [
        "GAYATRI VIDYA PARISHAD COLLEGE OF ENGINEERING", 
        "Gyatri Vidya Parishad College of Engineering (Autonomous)",
        "Gayatri Vidya Parishad College of Engineering (Autonomous)",
        "Gayatri Vidya Parishad College of engineering",
        "Gayatri Vidya Parishad College of Engineering"
    ],
    "Geethanjali College of Engineering and Technology": [
        "Geethanjali collage of engineering and technology"
    ],
    "Gitam University": [
        "Giatm","GITAM","Gitam University" "Gitam", "Gitam University Hyderabad Business School","GITAM","Global Institute of Technology And management"
    ],
    "Global Wealth University": [
        "Global wealth University Togo"
    ],
    "Gombe State University": [
        "Gombe State University  Tundun Wada Gombe State",
        "Gombe State University Tundun Wada Gombe State"
    ],
    "Graphic era hill university": [
        "Graphic Era Hill University Dehradun","Graphic Era Hill University  Dehradun",
        "Graphic Era Deemed to be University","Graphic era hill university","Graphic Era Deemed To be University"
    ],
    "Guru Nanak Dev University": [
        "Guru nanak dev University college verka"
    ],
    "Guru Nanak Institute of Technology": [
        "Guru Nanak Institute of Technology Nagpur"
        "Guru Nanak Institute of Technology  Nagpur", 
        "Gurunanak institute of technical campus", 
        "Gurunanak institutions of technical campus"
    ],
    "Gurukul Kangri Vishwavidyalaya": [
        "Gurukul kangri deemed to be university"
    ],
    "Hamdard University Karachi": [
        "hamdard university"
    ],
    "Hindustan Institute of Technology and Science": [
        "hindustan", 
        "Hindustan Institution of Technology and Science",
        "Hindusthan College of Engineering and Technology"
    ],
    "Ideal College": [
        "Ideal Institute of Engineering"
    ],
    "IIIT RK Valley": [
        "IIIT-RGUKT RK VALLEY"
    ],
    "IIT ISM Dhanbad": [
        "IIT(ISM) Dhanbad"
    ],
    "Illinois Institute of Technology": [
        "ill","iII",
        "Illinois Institute of Technolog", 
        "Illinois Institute of Technology","Illinois Institute of Techonology",
        "illinos institute of technology",
        "Illinois Institute of Technology Chicago",
        "illinois institution of technology",
        "Illinois Institute of Engineering", 
        "Illinois Institute of Technology  Chicago", 
        "illinois Institute of Technology Chicago", 
        "Illinois Institute of Technology", 
        "illinois Institute of Technology", 
        "illinois intitute of technology", 
        "Illinois Math and Science Academy", 
        "Illinois Tech University",
        "illinos institute of technology"
    ],
    "Imo State University": [
        "Imo State University Owerri","Imo State college of nursing and midwifery"
        #,"Imo State University Teaching Hospital Orlu"
    ],
    "Indian Institute of Public Health": [
        "Indian institute of public health Delhi"
    ],
    "Indian Institute of Technology Madras": [
        "Indian Institute of Technology  Madras",
        "Indian institute of technology madras",
        "Indian Institute of Technology Madras"
    ],
    "Institute of Business Administration": [
        "Institute of Business Administration (IBA) Karachi"
    ],
    "Institute of Management Sciences": [
        "Institute of Management Science Peshwar"
    ],
    "ITM SLS University": [
        "ITM SLS BARODA UNIVERSITY"
    ],
    "Jagran College of Arts Sciences and Commerce": [
        "jagran college of arts science and commerce"
    ],
    "Jamia Hamdard University": [
        "Jamia hamdard", "Jamia Hamdard",
        "Jamia hamdard New Delhi","Jamia hamdard  New Delhi"
    ],
    "Jawaharlal Nehru Technological University": [
        "Jawaharlal Nehru Technological University. Hyderabad India", 
        "Jawaharlal Nehru Technological University  Hyderabad  India",
        "Jawaharlal Nehru Technological University Hyderabad India",
        "Jawaharlal Nehru technological University Hyderabad", 
        "Jawaharlal Nehru Technological University of Hyderabad", 
        "Jawaharlal Technological University", 
        "JNTU", 
        "Jntu Kakinada", 
        "JNTUH","jntuh","JNTUH UCMH","JNTUHCEH"
    ],
    "Jamia Hamdard University":["Jamia Hamdard","Jamia hamdard  New Delhi"],
    
    "JB Institute of Engineering and Technology": [
        "JB INSTITUTE OF ENIGINEERING AND TECHNOLOGY"
    ],
    "JNTUK": [
        "Jntuk", 
        "JNTUK-University College of Engineering Vizianagaram"
    ],
    "K L University": [
        "KL University","Kl University"
        "K L Deemed to be University","KL Deemed to be University", 
        "Kl university", "Kl University",
        "Kluniversity"
    ],
    "Kaduna State University": [
        "Kaduna state University", 
        "Kaduna polytechnic", 
        "Kaduna State University  Kaduna",
        "Kaduna State University Kaduna"
    ],
    "Kafr Elsheikh University": [
        "Kafresheikh"
    ],
    "Kakatiya University": [
        "Kakatiya Institute of Technology", 
        "Kakatiya Institute of Technology of Science",
        "Kakatiya Institute of Technology and Sciences", 
        "Kakatiya Institute of Technology and Science",
        "Kakatiya Institute of Technology of Science"
    ],
    "Kakinada Institute of Engineering and Technology": [
        "Kakinada Institute of Engineering and Technology for women's"
    ],
    "Kano University of Science and Technology": [
        "Kano University of science and Technology wudil", 
        "Kano University of science and Technology  wudil"
    ],
    "Karunya Institute of Technology and Sciences": [
        "KARUNYA INSTITUTE OF TECHNOLOGY AND SCIENCES", 
        "KARUNYA INSTITUTION OF TECHNOLOGY AND SCIENCES",
        "KARUNYA INSTITUTION TECHNOLOGY AND SCIENCES",
        "Karunya University","Karunya university"
    ],
    "Kebbi State University of Science and Technology": [
        "Kebbi state University of science and technology aliero"
    ],
    "Kogi State University": [
        "Kogi State University  Anyigba", 
        "Kogi State University  Ayingba",
        "Kogi State University Anyigba", 
        "Kogi State University Ayingba"
    ],
    "Kwame Nkrumah University of Science and Technology": [
        "Kwame Nkrumah University of Science and Technology  KNUST", 
        "Kwame Nkrumah University of Science and Technology KNUST",
        "Kwame Nkrumah University of Science and Technology (KNUST)"
    ],
    "Kwara State University": [
        "kwara state polytechnic", 
        "kwara state university  malete Nigeria.", 
        "kwara state university malete Nigeria.",
        "Kwara State University  Malete.",
        "Kwara State University Malete."
    ],
    
    
    "Ladoke Akintola University of Technology": [
        "Ladoke Akintola of Technology  Ogbomoso", 
        "Ladoke Akintola of Technology Ogbomoso",
        "Ladoke Akintola University of University"
    ],
    "Lagos State University": [
        "Lagos State University (LASU)",
        "Lagos State University(LASU)"
    ],
    "Lincoln Way West": [
        "Lincoln Way west high school"
    ],
    "Lokmanya Tilak College of Engineering": [
        "LOKMANYA TILAK COLLEGE OF ENGINEERING",
        "LOKMANYA TILAK COLLEGE OF ENGINEERING  KOPERKHAIRNE",
        "LOKMANYA TILAK COLLEGE OF ENGINEERING KOPERKHAIRNE"
    ],
    "London Metropolitan University": [
        "London Metropolitan University  UK",
        "London Metropolitan University UK"
    ],
    "Lotus Valley International School": [
        "Lotus valley International", 
        "Lotus Valley International School  Noida", 
        "Lotus Valley International School Noida",
        "Lotus Valley International School  Noida  Uttar Pradesh",
        "Lotus Valley International School Noida Uttar Pradesh",
        "Lotus valley international school noida"
    ],
    "Lovely Professional University (LPU)": [
        "LPU", 
        "Lovely Professional University",
        "Lovely professional University",
        "Lovely Professional University(LPU)",
    ],
    "Mandanapalle institute of technology and science": [
        "Mandanapalli institute of technology & science", 
        "Mandanapalli institute of technology & science",
        "Mandanappale institute of technology and science"
    ],
    "Malla Reddy Institutions": [
        "Malla Reddy Engineering College", 
        "Malla Reddy College of Engineering", 
        "Malla Reddy College of Engineering and Technology", 
        "Malla Reddy University", 
        "MallaReddy Engineering college","Mallareddy Engineering college" 
        "Malla Reddy Engineering College For Women",
        "malla reddy engineering college","Mallareddy Engineering college",
    ],
    "Mangalore University": [
        "Mangalore Institute of Technology & Engineering",
        "Manglore Institute of Technology &Engineering"
    ],
    "Manipal University": [
        "Manipal university Dubai", 
        "manipal university jaipur"
    ],
    "Marri Laxman Reddy Institutions": [
        "marri laxman reddy", 
        "Marri Laxman reddy institute of pharmacy", 
        "Marri laxman Reddy institute of technology and management"
    ],
    "MDS University": [
        "MDS University  Ajmer  Rajasthan",
        "MDS University Ajmer Rajasthan"
    ],
    "Mehran University":[
        "Mehran University of Engineering and Technology",
        "Mehran UET SZAB Campus Khairpur Mir's Sindh Pakistan", 
        "Mehran uniiversity of engineering and technology Jamshoro pakistan", 
        "Mehran University Jamshoro Sindh Pakistan",
        "Mehran University of Engineering and Technology",
    ],
    "Methodist College of engineering and technology": [
        "Methodist Engineering Collge OU", 
        "Methodist University"
    ],
    "Michael Okpara University of Agriculture": [
        "MICHAEL OKAPARA UNIVERSITY OF  AGRICULTURE", 
        "Michael Okpara University of Agriculture  Umudike", 
        "Micheal Okpara University of Agriculture  Umudike", 
        "Michael Okpara University of Agriculture Umudike", 
        "Micheal Okpara University of Agriculture Umudike",
        "Michael Okpara University of Agriculture Umudike Abia State", 
        "Micheal Okpara University of Agriculture Umudike"
    ],
    "MIT-World Peace University (MIT-WPU)": [
        "MIT-WPU", 
        "MIT - WPU", 
        "mit", "MIT-World Peace University (MIT-WPU)",
        "MIT Arts commers and science college Alandi", 
        "MIT World Peace University", 
        "MIT Wpu","Mit Wpu",
    ],
    "Model Secondary School": [
        "Model secondary School amokwe",
        "Model secondary school amokwe"
    ],
    "MVSR Engineering College": [
        "MVSR ENGINEERING COLLEGE", 
        "MVSR Engineering"
    ],
    "MUSTuniversity":["must"],
    "Narayana Engineering College":["Narayana"],
    
    "National Open University of Nigeria": [
        "National Open University", 
        "National Open University Nigeria","National Open University  Nigeria",
        "National Open University of Nigeria"
    ],
    "National University of Science and Technology (Pakistan)": [
        "National University of Science and technology Islamabad", 
        "National University of Sciences and Technology",
        "National University of Science and Technology  Pakistan",
        "National University of Science and Technology Pakistan"
    ],
    "National University of Modern Languages Islamabad Pakistan":[
        "National University of Modern languages Islamabad (NUML)",
        "National University of Modern languages Islamabad(NUML)",
        "National University of Modern Languages Islamabad  Pakistan"
    ],
    
    "NED University of Engineering and Technology": [
        "NED", 
        "Ned University of science & Technology"
    ],
    "Nehru Institute of Engineering and Technology": [
        "Nehru Institute of engineering and technology coimbatore"
    ],
    "Niger Delta University": [
        "NIGER DELTA UNIVERSITY", 
        "Niger Delta University  Wilberforce island",
        "Niger Delta University Wilberforce island"
    ],
    "NIIT": [
        "NIIT  ACCRA","NIIT ACCRA"
    ],
    "Nnamdi Azikiwe University": [
        "NNAMDI AZIKIWE UNIVERSITY AWKA", 
        "Nnamdi Azikwe University",
        "Nnamdi Azikiwe University awka",
        "Nnamdi Azikiwe University  awka"
    ],

    "NMAMIT":["Nmamit Nitte"],
    
    "North maharashtra university": [
        "North Maharashtra University Jalgaon(M.H.)","North Maharashtra University  Jalgaon(M.H.)"
    ],
    "Pacific Academy of Higher Education and Research":[
        "Pacific Academy of Higher Educational and Research University"],
    "Parul University": [
        "parul institute of engineering and technology"
    ],
    "Patna Women's College": [
        "Patna womens college", 
        "PATNA WOMEN'S COLLEGE", 
        "Patna Women's College  Patna"
    ],
    "Pentecost University": [
        "Pentecost University College"
    ],
    "Petroleum Training Institute (PTI)": [
        "Petroleum Training Institute"
    ],
    "Pillai College of Engineering": [
        "Pillai College", 
        "pillai college of engineering"
    ],
    "Punjab Group of Colleges": [
        "Punjab college of science", 
        "Punjab group of college", 
        "Punjab group of colleges"
    ],
    "Punjab University": [
        "punjab university", 
        "Punjab university lahore"
    ],
    "Punjabi University": [
        "Punjabi university patiala"
    ],
    "Purdue University": [
        "purdue"
    ],
    "Presbyterian Boys' Secondary School":[
        "Presbyterian senior science school"],
    
    "Raghu Educational Institutions": [
        "Raghu Education College", 
        "Raghu Engineering College","Raghu engineering college"
    ],
    "Rajayalakshmi Institutions": [
        "Rajayalakshmi institute of technology", 
        "rajyalakshmi engineering college", 
        "rajayalakshmi engineering college",
        "Rajyalakshmi School of Business"
    ],
    "Rajiv Gandhi University of Knowledge Technologies (RGUKT)": [
        "Rajiv Gandhi Universities OF Knowledge And Technologies  RK Valley", 
        "Rajiv gandhi university of knowledge and technologies rk valley", 
        "Rajiv Gandhi Universities OF Knowledge And Technologies RK Valley", 
        "Rajiv Gandhi university of knowledge and technologies rk valley",
        "Rajiv Gandhi University of Knowledge Technologies  Nuzvid"
    ],
    "Ramadevi Women's University Bhubaneswar": [ 
        "Ramadevi Women's University  Bhubaneswar",
        "Ramadevi Women's University, Bhubaneswar",
        "Ramadevi Women's University,Bhubaneswar",
        "Ramadevi Women's University Bhubaneswar", 
        "Ramadevi women's University Bhubaneswar"
    ],
    "Ramjas College": [
        "Ramjas"
    ],
    "Redeemer's University": [
        "Redeemer's University Nigeria"
    ],
    "Rivers State University": [
        "River State University"
    ],
    "RVR & JC College of Engineering": [
        "RVR&jc", 
        "RVR & JC COLLEGE OF ENGINEERING"
    ],
    "R.C. Patel Institute Of Technology":["R.C.Patel Collge","R. C. Patel Institute Of Technology"],
    "Rani Durgawati University Jabalpur":["Rani durgavati vishwavidyalaya"],
    
    "Saint Louis University":["SAINT LOUIS","Saint Louis University","Saint Louis  University","saint louis university",
                   "Saint Louis","SAINT LOUIS",
                   "ST LOUIS UNIVERSITY","SAINT LOUIS UNIVERSITY",
                   "St. Louis University",
                   "Saint louis University",
                   "saint lious University", 
                   "SAINT LOUIS", "saint louis University",
                   "saint louis uinversity", "saint louis university","saint louis University", "Saint louis University", "Saint Louis Univercity", 
                   "Saint Louis Univeristy", "Saint Louis University","Saint Louis University  MO", "Saint Louis University MO","Saint Louis University  Saint Louis Missouri", "Saint Louis University Saint Louis Missouri",
                   "Saint Louis University I", "Saint Louis University Madrid", "Saint Louis University-Madrid", 
                   "Saint Louis University -Madrid", "Saint Louis Universty", 
                   "Saint louis universy", "Saint louis univesity", "Saint Louis Unniversity", "saint louis unveracity", 
                   "Saint Louise University", "Saint louisuniversity", "saint lousis university", "Saint Luis University", "Saint.louis university", 
                   "saintlouis", "Saint Louis University-Madrid","Saintlouis University", "SAINT LOUIS UNIVERSITY-MAIN CAMPUS",
                   "saintlouis university", "Saintlouis university","Saintlouis  University","Saintlouis University","St Louis",
                   "St Louis University", "Saintlouis  University","Saintlouis University","st. louis University"
                  ],
    "SIES":["SIES Graduate School of Technology"],
    "Sandip university": [
        "sandip institute of technology and research centre"
    ],
    "Sardar Patel University": [
        "Sardar Patel Institute of Technology"
    ],
    "Sathyabama University": [
        "Sathyabama institute of science and technology"
    ],
    "School of Nursing": [
        "School of nursing", 
        "School of Nursing  Ogun State",
        "School of Nursing Ogun State"
    ],
    "Seshadrirao Gudlavalleru Engineering College": [
        "seshadri rao gudlavalleru engineering college", 
        "Seshadri Ra","Seshadri Rao Gudlavalleru Engineering College",
    ],
    "Shri Ram College of Commerce": [
        "Shri Ram College Of Commerce  Delhi University",
        "Shri Ram College Of Commerce Delhi University"
    ],
    "Sikkim Manipal University": [
        "Sikkim manipal"
    ],
    "Southern New Hampshire University": [
        "Southern New Hampshire University via Kepler College", 
        "Southern New Hempshire University","Southern New Hamispshire University"
    ],
    "Sree Datta Institute of Engineering and Science": [
        "Sree dattha institute of Engineering and Science"
    ],
    "Sree Vidyanikethan Engineering College": [
        "Sree Vidyanikehan Engineering College",
        "Sree Visyanikehan Engineering College", 
        "Sree vidyanikethan college of pharmacy", 
        "sreevidyanikatan engineering college"
    ],
    "Sri Indu College of Engineering and Technology": [
        "Sri indhu college of engineering and technology", 
        "Sri indu", 
        "Sri Indu Institute of Engineering and Technology", 
        "Sri Indu Institute of management and technology"
    ],
    "Sri Krishna Institute of Technology": [
        "Sri Krishna Institution of Technology"
    ],
    "Sri Vasavi Engineering College": [
        "Sri Vasavi Institute of Engineering and Technology"
    ],
    "Sri Venkateswara College of Engineering and Technology": [
        "Sri venkateswara college of engineering"
    ],
    "SRM Institute of Science and Technology": [ "SRM University",
        "SRM UNIVERSITY", 
        "SRM University  AP", 
        "SRM UNIVERSITY  AP", 
        "SRM IST", 
        "SRM UNIVERSITY KTR", 
        "Srm", 
        "SRM Institute Of Science & Technology", 
        "SRM institute of science and technology", 
        "SRM Institute of Science and Technology"
    ],
    "SRM University Ramapuram chennai":["SRM Institute of Science and Tchnology Ramapuram",
                                        "SRM University"],
    "St. Joseph's Degree and PG College": [
        "ST. Joseph's Degree&PG College"
    ],
    "St. Francis College for Women": [
        "Sr.Francis College For Women", 
        "St.francis colloege for women"
    ],
    "Suez Canal University": [
        "Suez canal university", 
        "Suez Canal Uni"
    ],
    "Superior University": [
        "Superior group of college", 
        "Superior"
    ],
    "Swarnandhra Institute of Engineering and Technology": [
        "swarnandhra  institute of engineering and technology", 
        "swarnandhra institute of engineering and technology", 
        "swarnandhra institute of engg & technology", 
        "swarandhra"
    ],
    "Symbiosis International University": [
        "Symbiosis international university", 
        "Symbiosis Center for Distance Learning (SCDL)", 
        "Symbiosis Institute of Technology", 
        "Symbiosis international deemed university", 
        "Symboisis", 
        "Symbiosis Statistical Institute"
    ],

    "Southern New Hemisphere University":["Southern New Hemisphere University"],

    "The Oke Ogun Polytechnic":["The oke Ogun polytechnic saki oyo state"],
    
    "Umaru Musa Yaradua University Katsina Nigeria": [
        "Umaru Musa Yaradua University Katsina Nigeria", 
        "Umaru Musa Yaradua University Katsina  Nigeria",
        "Umaru Musa Yar'adua University Katsina"
    ],
    "University of Ghana":["University of Ghana Medical School"],
    "University of Agriculture Faisalabad": [
        "University of Agriculture Failabad Pakistan","University of Agriculture  Failabad  Pakistan"
    ],
    "University of Benin": [
        "university of Benin Edo State"
    ],
    "University of Calabar": [
        "University of calabar", 
        "University of Calabar  Calabar", 
        "university of Calabar  CRS Nigeria",
        "University of Calabar Calabar", 
        "university of Calabar CRS Nigeria"
    ],
    "University of Cape Coast": [
        "University of Capecoast"
    ],
    "University of Education Winneba": [
        "University of Education Winneba", 
        "University of Education   Winneba"
    ],
    "University of Engineering and technology Lahore": [
        "university of engineering and technology",
        "University of Engineering and technology"
    ],
    "University of Ibadan": [
        "University of Ibadan  Ibadan  Nigeria.",
        "University of Ibadan Ibadan Nigeria."
    ],
    "University of Ilorin": [
        "University of ilorin  Ilorin  Kwara State", 
        "University of ilorin  Ilorin Kwara State",
        "University of ilorin Ilorin Kwara State", 
        "University of ilorin Ilorin Kwara State",
        "UNIVERSITY OF ILORIN KWARA-NIGERIA"
    ],
    "UNIVERSITY OF ILLINOIS AT SPRINGFIELD":["University of Illinois Springfield"],
    
    "University of Lagos": [
        "University of Lagos  Nigeria",
        "University of Lagos Nigeria"
    ],
    "University of Maiduguri": [
        "University of Maiduguri Borno State"
    ],
    "University of Management and Technology": [
        "University of Management and Technology lahore Pakistan",
        "University of Management and Technology lahore  Pakistan"
    ],
    "University of Medical Sciences": [
        "University of medical science", 
        "University of Medical Sciences"
    ],
    "University of Mines and Technology": [
        "University of Mines and Technology  Tarkwa",
        "University of Mines and Technology Tarkwa"
    ],
    "University of Nigeria": ["University of Nigeria  Nsukka","University of Nigeria Nsukka",
        "University of Nigeria Nsukka"
    ],
    "University of Port Harcourt": [
        "University of Port Harcourt  Nigeria", "University of Port Harcourt Nigeria",
        "University of Portharcourt", 
        "University of Port-Harcourt","University of Port-harcourt"
    ],
    "University of the Punjab": [
        "University of the Punjab  Lahore",
        "University of the Punjab Lahore",
        "University of Punjab"
    ],
    "University of Uyo": [
        "University of Uyo Nigeria",
        "University of Uyo  Nigeria","University of Uyo Nigeria","University of oyo Akwaibom state",
        "University of oyo  Akwaibom state",
        "University of uyo  Akwaibom state","University of Uyo"
    ],
    "Velgapudi Ramakrishna siddhartha engineering college": [
        "Velgapudi Ramakrishna Siddhartha Engineering college","Velgapudi Ramakrishna siddhartha engineering  college","Velagapudi"
    ],
    "Vellore Institute of Technology": [
        "Vellore Institute of Technology  Vellore", "Vellore Institute of Technology Vellore",
        "Vellore Institute of Technology  Amaravati", 
        "Vellore Institute of Technology - Andhra Pradesh"
    ],
    "Vellore Institute of Technology Bhopal": [
        "Vellore Institute Of Technology  Bhopal", "Vellore Institute Of Technology Bhopal"
    ],
    "Vibgyor High": [
        "Vibguor High", 
        "Vibgyor High NIBM", 
        "vibgyor"
    ],
    "Vidya Pratishthan Kamalnayan Bajaj Institute of Engineering and Technology Baramati": [
        "Vidhya Pratishthan College of Engineering Baramati",
        "Vidya pratishthans kamal nayan bajaj institute of engineering and technology"
    ],
    "Vignan University": [
        "vignan", 
        "Vignan University for Science Research and technology", 
        "Vignans institute of information technology"
    ],
    "vignan's lara institute of technology and science": [
        "vignan's lara institute of technology and sciences"
        "vignan's lara institute of technology and science", 
        "Vignan's Lara Institute of Technology & Science", 
        "Vignan's Lara institute of technology and Sciences",
        "Vignan's Lara institute of technology and sciences"
    ],
    "Virtual University": [
        "Virtual University of Pakistan"
    ],
    "Visvesvaraya Technological University": [
        "Visveswaraya technical university"
    ],
    "VNR Vignana Jyothi Institute of Engineering": [
        "VNR Vignana Jyothi Institute of Engineering and Technology",
        "VNR Vignana Jyothi Institute of Enginnering",
        "Vnr Vignana jyothi institute of engineering and technology", 
        "VNRVJIET"
    ],
    "VPKBIET": [
        "VPKBIET  Baramati","VPKBIET Baramati"
    ],
    "Webster University": [
        "Webster"
    ],
    "VIT University":["VIT University  Vellore"
                     ],

    
    # Add more institutions as needed following the same structure...
}


'''# Function to standardize institution names based on state
def standardize_institution(row):
    for standardized_name, variations in institution_mapping.items():
        if row['Institution Name'] in variations:
            return standardized_name  # Return the standardized institution name
    return row['Institution Name']  # Return original if no match found

# Apply the function to standardize the 'Institution Name' column
df['Institution Name'] = df.apply(standardize_institution, axis=1)

# Print the DataFrame to confirm changes
print(df)
'''
# Function to standardize institution names based on state
def standardize_institution(row):
    for standardized_name, variations in institution_mapping.items():
        if row['Institution Name'] in variations:
            return standardized_name  # Return the standardized institution name
    return row['Institution Name']  # Return original if no match found

# Apply the function to standardize the 'Institution Name' column
df['Institution Name'] = df.apply(standardize_institution, axis=1)

In [103]:
df['Institution Name'].nunique()

1761

In [46]:
df.columns

Index(['Profile Id', 'Learner SignUp DateTime', 'Opportunity Id',
       'Opportunity Name', 'Opportunity Category', 'Opportunity End Date',
       'First Name', 'Last Name', 'Date of Birth', 'Gender', 'Mobile Number',
       'Address Line 1', 'Address Line 2', 'City', 'State', 'Country',
       'Zip Code', 'Institution Name', 'Graduation Date',
       'Current Student Status', 'Current/Intended Major', 'Entry created at',
       'Status Description', 'Status Code', 'Apply Date',
       'Opportunity Start Date', 'Reward Awarded Date', 'Completion Date',
       'Reward Amount', 'Badge Id', 'Badge Name', 'Skill Points Earned',
       'Skills Earned', 'Countries'],
      dtype='object')

Feature Engineering

address 1 and Address 2 columns

In [189]:
df['Full_Address'] = df['Address Line 1'].fillna('') + ' ' + df['Address Line 2'].fillna('')
df['Full_Address'] = df['Full_Address'].str.strip()  # Remove extra spaces if any

In [59]:
df.columns

Index(['Profile Id', 'Learner SignUp DateTime', 'Opportunity Id',
       'Opportunity Name', 'Opportunity Category', 'Opportunity End Date',
       'First Name', 'Last Name', 'Date of Birth', 'Gender', 'Mobile Number',
       'Address Line 1', 'Address Line 2', 'City', 'State', 'Country',
       'Zip Code', 'Institution Name', 'Graduation Date',
       'Current Student Status', 'Current/Intended Major', 'Entry created at',
       'Status Description', 'Status Code', 'Apply Date',
       'Opportunity Start Date', 'Reward Awarded Date', 'Completion Date',
       'Reward Amount', 'Badge Id', 'Badge Name', 'Skill Points Earned',
       'Skills Earned', 'Countries', 'Full_Address'],
      dtype='object')

Adding First name and Last name columns together

In [190]:
df['Full_Name'] = df['First Name'].fillna('') + ' ' + df['Last Name'].fillna('')
df['Full_Name'] = df['Full_Name'].str.strip()  # Remove extra spaces

In [191]:
# Ensure 'Date of Birth' is in datetime format
df['Date of Birth'] = pd.to_datetime(df['Date of Birth'], errors='coerce')

# Calculate the age in years
df['Age'] = (datetime.now() - df['Date of Birth']).dt.days // 365

# Display the first few rows of the 'Age' column
df['Age'].head()

0    23
1    24
2    22
3    24
4    24
Name: Age, dtype: int64

Extracting Engagement Duration to know how many days he has been engaged on this platform,

In [192]:
# Ensure 'Completion Date' and 'Apply Date' are in datetime format
df['Completion Date'] = pd.to_datetime(df['Completion Date'], errors='coerce')
df['Apply Date'] = pd.to_datetime(df['Apply Date'], errors='coerce')

# Filter out rows where 'Completion Date' is 01-01-1900
mask = df['Completion Date'] != pd.Timestamp('1900-01-01')

# Calculate engagement duration for valid dates only
df.loc[mask, 'Engagement Duration'] = (df['Completion Date'] - df['Apply Date']).dt.days

# Set 'Engagement Duration' to NaN for excluded rows (optional)
df.loc[~mask, 'Engagement Duration'] = pd.NA

# Display the first few rows
df[['Completion Date', 'Apply Date', 'Engagement Duration']].head()

  Completion Date Apply Date  Engagement Duration
0      1900-01-01 2023-06-14                  NaN
1      1900-01-01 2023-05-01                  NaN
2      1900-01-01 2023-05-11                  NaN
3      1900-01-01 2023-10-09                  NaN
4      1900-01-01 2023-01-06                  NaN

In [37]:
df['Engagement Duration'].unique()

array([ nan,  89.,   1.,   5.,  25.,   4.,  12.,  10., 112.,   2., 123.,
       115., 172., 187.,  21.,  68.,  52., 146., 197., 184.,  24., 138.,
       183.,  33.,  18.])

In [38]:
df['Engagement Duration'].mean()

74.79310344827586

In [45]:
# Save the cleaned DataFrame to a CSV file
df.to_csv(r"C:\Users\vamsh\Downloads\cleaned_data_sample.csv", index=False)

# Confirm that the file is saved
print("CSV file saved successfully!")

CSV file saved successfully!

In [40]:
df.columns

Index(['Profile Id', 'Learner SignUp DateTime', 'Opportunity Id',
       'Opportunity Name', 'Opportunity Category', 'Opportunity End Date',
       'First Name', 'Last Name', 'Date of Birth', 'Gender', 'Mobile Number',
       'Address Line 1', 'Address Line 2', 'City', 'State', 'Country',
       'Zip Code', 'Institution Name', 'Graduation Date',
       'Current Student Status', 'Current/Intended Major', 'Entry created at',
       'Status Description', 'Status Code', 'Apply Date',
       'Opportunity Start Date', 'Reward Awarded Date', 'Completion Date',
       'Reward Amount', 'Badge Id', 'Badge Name', 'Skill Points Earned',
       'Skills Earned', 'Full_Address', 'Full_Name', 'Age',
       'Engagement Duration'],
      dtype='object')

In [193]:
# Drop the specified columns
df = df.drop(['First Name', 'Last Name', 'Address Line 1', 'Address Line 2', 'Engagement Duration'], axis=1)

In [47]:
# Drop the specified columns
#df = df.drop(['First Name', 'Last Name', 'Address Line 1', 'Address Line 2', 'Engagement Duration'], axis=1)

# Save the updated DataFrame to a CSV file
df.to_csv(r"C:\Users\vamsh\Downloads\cleaned_data_sample.csv", index=False)

print("Columns dropped and DataFrame saved to 'cleaned_data.csv'")

Columns dropped and DataFrame saved to 'cleaned_data.csv'

In [144]:
df.columns

Index(['Profile Id', 'Learner SignUp DateTime', 'Opportunity Id',
       'Opportunity Name', 'Opportunity Category', 'Opportunity End Date',
       'Date of Birth', 'Gender', 'Mobile Number', 'City', 'State', 'Country',
       'Zip Code', 'Institution Name', 'Graduation Date',
       'Current Student Status', 'Current/Intended Major', 'Entry created at',
       'Status Description', 'Status Code', 'Apply Date',
       'Opportunity Start Date', 'Reward Awarded Date', 'Completion Date',
       'Reward Amount', 'Badge Id', 'Badge Name', 'Skill Points Earned',
       'Skills Earned', 'Full_Address', 'Full_Name', 'Age'],
      dtype='object')

In [194]:
# Replace numeric-only entries with 'No address' or 'Wrong address'
df['Full_Address'] = df['Full_Address'].apply(
    lambda x: 'No address' if x.isdigit() else x
)

In [147]:
df.nunique()

Profile Id                 3964
Learner SignUp DateTime     414
Opportunity Id               23
Opportunity Name             22
Opportunity Category          5
Opportunity End Date         16
Date of Birth              2620
Gender                        4
Mobile Number              3834
City                       1156
State                       525
Country                      71
Zip Code                   1861
Institution Name           1761
Graduation Date             242
Current Student Status        4
Current/Intended Major      406
Entry created at             94
Status Description            8
Status Code                   8
Apply Date                  442
Opportunity Start Date       26
Reward Awarded Date           9
Completion Date               9
Reward Amount                 3
Badge Id                      5
Badge Name                    5
Skill Points Earned           5
Skills Earned                 5
Full_Address               3819
Full_Name                  3844
Age                          44
dtype: int64

In [148]:
print(df['Entry created at'].unique())

['03/11/2024 12:01:41' '03/11/2024 12:01:42' '03/11/2024 12:01:43'
 '03/11/2024 12:01:44' '03/11/2024 12:01:45' '03/11/2024 12:01:46'
 '03/11/2024 12:01:47' '03/11/2024 12:01:48' '03/11/2024 12:01:49'
 '03/11/2024 12:01:50' '03/11/2024 12:01:51' '03/11/2024 12:01:52'
 '03/11/2024 12:01:53' '03/11/2024 12:01:54' '03/11/2024 12:01:55'
 '03/11/2024 12:01:56' '03/11/2024 12:01:57' '03/11/2024 12:01:58'
 '03/11/2024 12:01:59' '03/11/2024 12:02:00' '03/11/2024 12:02:01'
 '03/11/2024 12:02:02' '03/11/2024 12:02:03' '03/11/2024 12:02:04'
 '03/11/2024 12:02:05' '03/11/2024 12:02:06' '03/11/2024 12:02:07'
 '03/11/2024 12:02:08' '03/11/2024 12:02:09' '03/11/2024 12:02:10'
 '03/11/2024 12:02:11' '03/11/2024 12:02:12' '03/11/2024 12:02:13'
 '03/11/2024 12:02:14' '03/11/2024 12:02:15' '03/11/2024 12:02:16'
 '03/11/2024 12:02:17' '03/11/2024 12:02:18' '03/11/2024 12:02:19'
 '03/11/2024 12:02:20' '03/11/2024 12:02:21' '03/11/2024 12:02:22'
 '03/11/2024 12:02:23' '03/11/2024 12:02:24' '03/11/2024 12:02:25'
 '03/11/2024 12:02:26' '03/11/2024 12:02:27' '03/11/2024 12:02:28'
 '03/11/2024 12:02:29' '03/11/2024 12:02:30' '03/11/2024 12:02:31'
 '03/11/2024 12:02:32' '03/11/2024 12:02:33' '03/11/2024 12:02:34'
 '03/11/2024 12:02:35' '03/11/2024 12:02:36' '03/11/2024 12:02:37'
 '03/11/2024 12:02:38' '03/11/2024 12:02:39' '03/11/2024 12:02:40'
 '03/11/2024 12:02:41' '03/11/2024 12:02:42' '03/11/2024 12:02:43'
 '03/11/2024 12:02:44' '03/11/2024 12:02:45' '03/11/2024 12:02:46'
 '03/11/2024 12:02:47' '03/11/2024 12:02:48' '03/11/2024 12:02:49'
 '03/11/2024 12:02:50' '03/11/2024 12:02:51' '03/11/2024 12:02:52'
 '03/11/2024 12:02:53' '03/11/2024 12:02:54' '03/11/2024 12:02:55'
 '03/11/2024 12:02:56' '03/11/2024 12:02:57' '03/11/2024 12:02:58'
 '03/11/2024 12:02:59' '03/11/2024 12:03:00' '03/11/2024 12:03:01'
 '03/11/2024 12:03:02' '03/11/2024 12:03:03' '03/11/2024 12:03:04'
 '03/11/2024 12:03:05' '03/11/2024 12:03:06' '03/11/2024 12:03:07'
 '03/11/2024 12:03:08' '03/11/2024 12:03:09' '03/11/2024 12:03:10'
 '03/11/2024 12:03:11' '03/11/2024 12:03:12' '03/11/2024 12:03:13'
 '03/11/2024 12:03:14']

In [195]:
df['Entry created at'] = pd.to_datetime(df['Entry created at']).dt.floor('min')
print(df['Entry created at'].value_counts())

Entry created at
2024-03-11 12:02:00    5455
2024-03-11 12:01:00    1705
2024-03-11 12:03:00    1398
Name: count, dtype: int64

In [151]:
df.nunique()

Profile Id                 3964
Learner SignUp DateTime     414
Opportunity Id               23
Opportunity Name             22
Opportunity Category          5
Opportunity End Date         16
Date of Birth              2620
Gender                        4
Mobile Number              3834
City                       1156
State                       525
Country                      71
Zip Code                   1861
Institution Name           1761
Graduation Date             242
Current Student Status        4
Current/Intended Major      406
Entry created at              3
Status Description            8
Status Code                   8
Apply Date                  442
Opportunity Start Date       26
Reward Awarded Date           9
Completion Date               9
Reward Amount                 3
Badge Id                      5
Badge Name                    5
Skill Points Earned           5
Skills Earned                 5
Full_Address               3819
Full_Name                  3844
Age                          44
dtype: int64

In [153]:
# Save the updated DataFrame to a CSV file
df.to_csv(r"C:\Users\vamsh\Downloads\cleaned_data_sample.csv", index=False)
print("Dataset saved successfully")

Dataset saved successfully

In [152]:
df.columns

Index(['Profile Id', 'Learner SignUp DateTime', 'Opportunity Id',
       'Opportunity Name', 'Opportunity Category', 'Opportunity End Date',
       'Date of Birth', 'Gender', 'Mobile Number', 'City', 'State', 'Country',
       'Zip Code', 'Institution Name', 'Graduation Date',
       'Current Student Status', 'Current/Intended Major', 'Entry created at',
       'Status Description', 'Status Code', 'Apply Date',
       'Opportunity Start Date', 'Reward Awarded Date', 'Completion Date',
       'Reward Amount', 'Badge Id', 'Badge Name', 'Skill Points Earned',
       'Skills Earned', 'Full_Address', 'Full_Name', 'Age'],
      dtype='object')

In [154]:
#df[col] = pd.to_datetime(df[col], errors='coerce')
#Calculate Opportunity Duration (in Days)
df['Opportunity Duration (days)'] = (df['Opportunity End Date'] - df['Opportunity Start Date']).dt.days

AttributeError: Can only use .dt accessor with datetimelike values

In [196]:
# Convert columns to datetime format if they're not already
date_columns = [
    'Opportunity Start Date', 
    'Opportunity End Date', 
    'Apply Date', 
    'Entry created at', 
    'Completion Date'
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')  # Convert to datetime, setting invalid parsing to NaT

# 1. Calculate Opportunity Duration (in Days)
df['Opportunity Duration (days)'] = (df['Opportunity End Date'] - df['Opportunity Start Date']).dt.days

In [197]:

# 2. Time Taken to Apply (in Days)
df['Time to Apply (days)'] = (df['Entry created at'] - df['Apply Date']).dt.days

In [ ]:
for col in date_columns:
    df[col] = df[col].dt.strftime('%Y-%m-%d')  # Change to desired string format

# Verify the DataFrame
print(df.head())

In [198]:
df.head()

,Profile Id,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,Date of Birth,Gender,Mobile Number,City,...,Reward Amount,Badge Id,Badge Name,Skill Points Earned,Skills Earned,Full_Address,Full_Name,Age,Opportunity Duration (days),Time to Apply (days)
0,004b8a25-17d4-4e9a-a41b-b5336327e170,2023-06-14,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29,2001-01-12,Female,+923441950694',Peshawar,...,0,NaN,NaN,0,NaN,Peshwar,Faria Khan,23,604,271
1,00628747-9775-4a85-a179-4d5007ccb8b7,2023-05-01,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29,2000-08-16,Female,+919381442895',vikarabad,...,0,NaN,NaN,0,NaN,H.no 18/4 sultanpur village Bantwaram (manda)...,Poojitha Bembadi,24,604,315
2,00841155-6c62-4f83-b165-57ba0df9c031,2023-04-09,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29,2002-01-27,Male,+17734572192',Chicago,...,0,NaN,NaN,0,NaN,2525 N Clark St Apt E,Emmanuel Thompson,22,604,305
3,00f5161c-ba85-472d-9b0a-3301aac78598,2023-08-29,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29,1999-11-01,Female,+13143350542',Saint Louis,...,0,NaN,NaN,0,NaN,4404 McPherson Avenue,Amrutha Varshini Anagurthi,24,604,154
4,01273a5e-fcc5-4b1a-a637-19aff497dac1,2023-01-06,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,2024-06-29,2000-04-19,Male,+917032055646',Saint Louis,...,0,NaN,NaN,0,NaN,4340 c12 maryland eve Maryland lofts,Vinay Varshith Pechetti,24,604,430

In [199]:
# Save the updated DataFrame to a CSV file
df.to_csv(r"C:\Users\vamsh\Downloads\cleaned_data_sample.csv", index=False)
print("Dataset saved successfully")

Dataset saved successfully